/-
Copyright (c) 2026 Fabian Franz. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Fabian Franz
-/
module

public import Mathlib.GroupTheory.Subgroup.Centralizer

/-!
# Commutative groups from generating sets

A group generated by a pairwise-commuting set is commutative. The additive counterpart is generated
automatically.
-/

@[expose] public section

namespace Subgroup

/-- A group generated by a pairwise-commuting set is commutative. -/
@[to_additive /-- An additive group generated by a pairwise-commuting set is commutative. -/]
theorem isMulCommutative_of_closure_eq_top {G : Type*} [Group G] {s : Set G}
    (hs : closure s = ⊤) (hcomm : ∀ x ∈ s, ∀ y ∈ s, x * y = y * x) :
    IsMulCommutative G := by
  let hclosure : IsMulCommutative (closure s) := isMulCommutative_closure hcomm
  apply IsMulCommutative.of_comm
  intro x y
  have hx : x ∈ closure s := by rw [hs]; exact mem_top x
  have hy : y ∈ closure s := by rw [hs]; exact mem_top y
  exact congr_arg Subtype.val (@mul_comm' (closure s) _ hclosure ⟨x, hx⟩ ⟨y, hy⟩)

end Subgroup
