import Lib.Algebra.Homology.MayerVietorisShortExact
import Lib.Topology.Homotopy.Suspension
import Lib.Topology.Algebra.FreeActionLocus
import Lib.Topology.OnePointCollapse
import Lib.AlgebraicTopology.SingularHomology.Chains
import Lib.AlgebraicTopology.SingularHomology.ModuleHomology
import Lib.AlgebraicTopology.SingularHomology.MayerVietoris
import Lib.AlgebraicTopology.SingularHomology.HomotopyInvariance
import Lib.AlgebraicTopology.SingularHomology.Suspension
import Lib.AlgebraicTopology.SingularHomology.Sum
import Lib.AlgebraicTopology.SingularHomology.Torus
import Lib.AlgebraicTopology.SingularHomology.CircleProduct
import Lib.AlgebraicTopology.SingularHomology.Pontryagin
import Lib.AlgebraicTopology.SingularHomology.Sphere
import Lib.AlgebraicTopology.SingularHomology.SphereHomology
import Lib.AlgebraicTopology.SingularHomology.SuspensionCover
import Lib.AlgebraicTopology.SingularHomology.Coproduct
import Lib.AlgebraicTopology.SingularHomology.LocalContributions
import Lib.AlgebraicTopology.SingularHomology.Naturality
import Lib.AlgebraicTopology.SingularHomology.LocalDegree
import Lib.AlgebraicTopology.SingularHomology.LinearSphereAction
import Lib.Geometry.Manifold.Morse.Handle
import Lib.Analysis.Calculus.MorseLemma
import Lib.Geometry.Manifold.Flow.Compact
import Lib.Geometry.Manifold.RegularLevel
import Lib.Geometry.Manifold.Morse.HandleAttachment
import Lib.Geometry.Manifold.Morse.Cubic
import Lib.Geometry.Manifold.Morse.CubicFlow
import Lib.Geometry.Manifold.Transversality.Basic
import Lib.Geometry.Manifold.Immersion.Relative
import Lib.Geometry.Manifold.Morse.Rearrangement
import Lib.Geometry.Manifold.Morse.Connection
import Lib.Geometry.Manifold.Morse.Cancellation
import Lib.Geometry.Manifold.Morse.RearrangementTheorem
import Lib.Geometry.Manifold.Morse.Birth
import Lib.Geometry.Manifold.Flow.HeightTranslating
import Lib.Geometry.Manifold.Morse.Existence
import Lib.Analysis.ODE.SmoothFlow
import Lib.Geometry.Manifold.ChartedSpace.Transport
import Lib.Topology.Homotopy.CylinderHEP
import Lib.AlgebraicTopology.FundamentalGroup.SimplyConnectedCover
import Lib.AlgebraicTopology.FundamentalGroup.TwoSimplyConnectedCover
import Lib.AlgebraicTopology.FundamentalGroup.VanKampen
import Lib.AlgebraicTopology.FundamentalGroupoid.SimplyConnectedSphere
import Lib.Topology.Homotopy.HandleRetraction
import Lib.Topology.Homotopy.LoopSubdivision
import Lib.Topology.MappingTorus.Basic
import Lib.Geometry.Manifold.Morse.SublevelSets
import Lib.Geometry.Manifold.Morse.Index
import Lib.Analysis.Complex.Mobius
import Lib.Geometry.Manifold.Instances.RiemannSphere
import Lib.Analysis.Complex.SchwarzReflection
import Lib.Analysis.Complex.RiemannMapping
import Lib.Analysis.Complex.RiemannMapping.Steps
import Lib.Analysis.Complex.Cousin
import Lib.Analysis.Complex.SquareRoot
import Lib.Geometry.Manifold.Complex.Biholomorph
import Lib.Geometry.Manifold.WhitneyEmbedding
import Lib.Geometry.Manifold.Whitney.BigonModel
import Lib.Geometry.Manifold.Morse.CircleGluing
import Lib.Geometry.Manifold.Whitney.CleanStrips
import Lib.Geometry.Manifold.Whitney.AnnularExtension
import Lib.Geometry.Manifold.Whitney.FrameField
import Lib.Geometry.Manifold.Whitney.EmbeddedArcs
import Lib.Geometry.Manifold.Whitney.RankThreeModel
import Lib.Geometry.Manifold.Morse.BeltCancellation
import Lib.Geometry.Manifold.VectorBundle.ProjectionBundle
import Lib.Geometry.Manifold.Collar
import Lib.Geometry.Manifold.Morse.SurgeryWindows
import Lib.Geometry.Manifold.Quotient.Atlas
import Lib.Geometry.Manifold.Quotient.LocalOrbit
import Lib.Topology.Homotopy.CellAttachment
import Lib.Topology.Homotopy.CellFilling
import Lib.Geometry.Manifold.Morse.CellStructure
import Lib.Geometry.Manifold.Morse.MinimalSystem
import Lib.Geometry.Manifold.Morse.Reeb
import Lib.Geometry.Manifold.Morse.CutTransport
import Lib.Geometry.Manifold.Morse.MiddleBlocks
import Lib.Algebra.Group.Filtration
import Lib.LinearAlgebra.Matrix.TransvectionReduction
import Lib.Algebra.Module.IntegerPresentation
import Lib.AlgebraicTopology.Hurewicz.SimplexCube
import Lib.AlgebraicTopology.Hurewicz.HomotopyExtension
import Lib.AlgebraicTopology.Hurewicz.CubeTriangulation
import Lib.AlgebraicTopology.Hurewicz.PrismOperator
import Lib.AlgebraicTopology.Hurewicz.Subdivision
import Lib.AlgebraicTopology.Hurewicz.CubeGluing
import Lib.AlgebraicTopology.Hurewicz.Degree
import Lib.AlgebraicTopology.Hurewicz.CubeChainDecomposition
import Lib.AlgebraicTopology.Hurewicz.Straightening
import Lib.AlgebraicTopology.Hurewicz.CubeSphere
import Lib.AlgebraicTopology.Hurewicz.HopfDegree
import Lib.AlgebraicTopology.Hurewicz.Naturality
import Lib.AlgebraicTopology.Hurewicz.DegreeSix
import Lib.Topology.Homeomorph.DiskCube
import Lib.AlgebraicTopology.Hurewicz.CycleClasses
import Lib.AlgebraicTopology.Hurewicz.Degree1
import Lib.AlgebraicTopology.Hurewicz.H1Character
import Lib.AlgebraicTopology.Hurewicz.PeriodicLoop
import Lib.AlgebraicTopology.Hurewicz.SimplexPaths
import Lib.GroupTheory.Abelianization.SemidirectProduct
import Lib.GroupTheory.GroupExtension.Abelianization
import Lib.GroupTheory.GeneratingSet
import Lib.LinearAlgebra.CyclicAverage
import Lib.LinearAlgebra.FreeModule.Finite.CardQuotient
import Lib.LinearAlgebra.FreeModule.RankTwoCokernel
import Lib.LinearAlgebra.SquareZero
import Lib.LinearAlgebra.ExteriorPower.MinorCoordinates
import Lib.GroupTheory.SplitExtension
import Lib.GroupTheory.PresentedGroup.CentralTwist
import Lib.Topology.FiberBundle.TwoOpenTransition
import Lib.Topology.Covering.Quotient
import Lib.Topology.Covering.DiagonalQuotient
import Lib.Topology.Covering.InvariantSubset
import Lib.Topology.Homotopy.SublevelRetraction
import Lib.Topology.Homotopy.LocalCollapse
import Lib.Topology.MappingTorus.HomologyCover
import Lib.Topology.MappingTorus.Wang
import Lib.AlgebraicTopology.SingularHomology.CrossInsert
import Lib.AlgebraicTopology.SingularHomology.CrossProduct
import Lib.AlgebraicTopology.SingularHomology.PathClass
import Lib.AlgebraicTopology.SingularHomology.CirclePaths
import Lib.AlgebraicTopology.SingularHomology.TorusCoordinates
import Lib.AlgebraicTopology.SingularHomology.FirstHurewicz
import Lib.AlgebraicTopology.SingularHomology.LocalContributionsNaturality
import Lib.AlgebraicTopology.SingularHomology.LocalDegreeNeighborhoods
import Lib.Geometry.Manifold.Morse.RearrangementAmbient
import Lib.AlgebraicTopology.SingularHomology.OnePointCover
import Lib.Geometry.Manifold.Morse.SurgeryHomology
import Lib.Geometry.Manifold.Morse.OrderedCancellation
import Lib.Geometry.Manifold.Morse.AdaptedWindows
import Lib.Geometry.Manifold.Morse.SurgeryCollapse

/-!
# Reusable V10 Section 6 library

This root exports proof-independent mathematics extracted from checked V10 modules and checked in
the Hopf development. Files below `Lib/` do not import `S6Shortcuts`, `S6`, `Hopf`, `Challenge`,
or `Solution`; proof-specific data and adapters live downstream.

The exported modules contain the reusable algebraic results formalized from V10 Section 6. Results
which still lack a Lean proof are documented as gaps rather than represented by placeholders.
-/
