/-
Transitional namespace shims for extraction lane A (decision Q2).

The five namespaces renamed in this lane kept their historical dotted paths
for the renamed families via the `export` aliases below, so `Hopf/` modules
with hundreds of references to the old names stay green until the owner's
de-shim pass. The `Mathoverflow1973` wrapper itself is gone from the tree
(2026-09-13); these are family-rename aliases only. Delete this file together
with the shims' consumers once the renames are absorbed.
-/

import Lib.Algebra.Homology.MayerVietorisShortExact
import Lib.AlgebraicTopology.SingularHomology.ModuleHomology
import Lib.AlgebraicTopology.SingularHomology.Chains
import Lib.AlgebraicTopology.SingularHomology.MayerVietoris
import Lib.AlgebraicTopology.SingularHomology.HomotopyInvariance
import Lib.AlgebraicTopology.Hurewicz.HopfDegree
import Lib.Topology.Homotopy.Suspension
import Lib.AlgebraicTopology.SingularHomology.Sphere
import Lib.AlgebraicTopology.SingularHomology.Suspension
import Lib.AlgebraicTopology.SingularHomology.Sum
import Lib.AlgebraicTopology.SingularHomology.CircleProduct
import Lib.AlgebraicTopology.SingularHomology.CrossInsert
import Lib.AlgebraicTopology.SingularHomology.PathClass
import Lib.AlgebraicTopology.SingularHomology.SphereHomology
import Lib.Topology.OnePointCollapse
import Lib.AlgebraicTopology.SingularHomology.Coproduct
import Lib.AlgebraicTopology.SingularHomology.LocalContributions
import Lib.AlgebraicTopology.SingularHomology.Naturality
import Lib.AlgebraicTopology.SingularHomology.LocalDegree
import Lib.Topology.Homotopy.CellAttachment
import Lib.Topology.Homotopy.SublevelRetraction
import Lib.Topology.Homotopy.LocalCollapse
import Lib.AlgebraicTopology.Hurewicz.SimplexCube
import Lib.AlgebraicTopology.Hurewicz.HomotopyExtension
import Lib.AlgebraicTopology.Hurewicz.CubeSphere

export SingularChains (ChainHomology.Boundaries1 ChainHomology.Cycle1 ChainHomology.Opchains ChainHomology.ShortBoundaries ChainHomology.ShortCycle ChainHomology.ShortOpchains ChainHomology.boundaries1_le_ker ChainHomology.boundaryCycle1 ChainHomology.chainClass ChainHomology.chainClass_boundary ChainHomology.chainClass_eq_iff ChainHomology.cycleClass ChainHomology.cycleClass_eq_zero_iff ChainHomology.cycleClass_surjective ChainHomology.homologyDesc ChainHomology.homologyDesc_cycleClass ChainHomology.homologyMap_cycleClass ChainHomology.homologyToChainClass ChainHomology.homologyToChainClass_cycleClass ChainHomology.homologyToChainClass_injective ChainHomology.mapCycles ChainHomology.mapCycles_val ChainHomology.mkCycle1 ChainHomology.opchainsEquiv ChainHomology.opchainsModule ChainHomology.range_sc_one_f ChainHomology.shortCycleClass ChainHomology.shortCycleClass_eq_zero_iff ChainHomology.shortCycleClass_surjective ChainHomology.shortCycleModule ChainHomology.shortHomologyToChainClass ChainHomology.shortHomologyToChainClass_cycleClass ChainHomology.shortHomologyToChainClass_injective ChainHomology.shortMap ChainHomology.shortOpchainsModule Chains Cycles1 Opchains Simplex SingularH1 SingularSimplex boundaryCycle boundaryOne boundaryOne_loop boundaryOne_pathChain boundaryOne_simplex boundaryTwo boundaryTwo_concatChain boundaryTwo_constantTriangleChain boundaryTwo_correctedHomotopyChain boundaryTwo_homotopyChain boundaryTwo_loopHomotopy boundaryTwo_simplex boundary_simplex chainBasis chainBasis_apply chainBasis_coe chainBasis_repr chainClass chainClass_boundary chainClass_eq_iff chainLift chainLift_simplex chainMap_ext chainsEquivFinsupp chainsFromFinsupp chainsFromFinsupp_comp_repr chainsFromFinsupp_single chainsRepr chainsRepr_comp_fromFinsupp chainsRepr_simplex concatChain concatSimplex concatSimplex_apply concatSimplex_face_one concatSimplex_face_two concatSimplex_face_zero concatTime constantEdgeChain constantTriangleChain correctedHomotopyChain cycleClass cycleClass_surjective cycleVal cycles1Module cycles1_boundary homologyDesc homologyDescOfChain homologyDescOfChain_cycleClass homologyDesc_cycleClass homologyToChainClass homologyToChainClass_cycleClass homologyToChainClass_injective homotopyChain homotopyDiagonalSimplex homotopyLowerSimplex homotopyLowerSimplex_face_one homotopyLowerSimplex_face_two homotopyLowerSimplex_face_zero homotopyUpperSimplex homotopyUpperSimplex_face_one homotopyUpperSimplex_face_two homotopyUpperSimplex_face_zero inducedChain inducedChain_boundary inducedChain_comp inducedChain_id inducedChain_simplex inducedCycles inducedCycles_val inducedHomology inducedHomology_comp inducedHomology_cycleClass inducedHomology_id lowerTriangleMap lowerTriangle_face_one lowerTriangle_face_two lowerTriangle_face_zero mem_simplex_span_iff mkCycle1 opchainsModule pathChain pathChain_refl pathSimplex pathSimplex_face_one pathSimplex_face_zero pathSimplex_simplexPath pathSimplex_vertex_one pathSimplex_vertex_zero pointChain simplexChain simplexChain_span simplexCoordinate simplexFace simplexFace_apply simplexFace_apply_self simplexFace_apply_succAbove simplexFace_one_one simplexFace_one_two simplexFace_one_zero simplexFace_zero_one simplexFace_zero_zero simplexIndex simplexIndex_face simplexPath simplexZero_eq_vertex simplex_span_inter singularChainMap singularComplex upperTriangleMap upperTriangle_face_one upperTriangle_face_two upperTriangle_face_zero)
namespace FirstHurewicz
export SingularChains (ChainHomology.Boundaries1 ChainHomology.Cycle1 ChainHomology.Opchains ChainHomology.ShortBoundaries ChainHomology.ShortCycle ChainHomology.ShortOpchains ChainHomology.boundaries1_le_ker ChainHomology.boundaryCycle1 ChainHomology.chainClass ChainHomology.chainClass_boundary ChainHomology.chainClass_eq_iff ChainHomology.cycleClass ChainHomology.cycleClass_eq_zero_iff ChainHomology.cycleClass_surjective ChainHomology.homologyDesc ChainHomology.homologyDesc_cycleClass ChainHomology.homologyMap_cycleClass ChainHomology.homologyToChainClass ChainHomology.homologyToChainClass_cycleClass ChainHomology.homologyToChainClass_injective ChainHomology.mapCycles ChainHomology.mapCycles_val ChainHomology.mkCycle1 ChainHomology.opchainsEquiv ChainHomology.opchainsModule ChainHomology.range_sc_one_f ChainHomology.shortCycleClass ChainHomology.shortCycleClass_eq_zero_iff ChainHomology.shortCycleClass_surjective ChainHomology.shortCycleModule ChainHomology.shortHomologyToChainClass ChainHomology.shortHomologyToChainClass_cycleClass ChainHomology.shortHomologyToChainClass_injective ChainHomology.shortMap ChainHomology.shortOpchainsModule Chains Cycles1 Opchains Simplex SingularH1 SingularSimplex boundaryCycle boundaryOne boundaryOne_loop boundaryOne_pathChain boundaryOne_simplex boundaryTwo boundaryTwo_concatChain boundaryTwo_constantTriangleChain boundaryTwo_correctedHomotopyChain boundaryTwo_homotopyChain boundaryTwo_loopHomotopy boundaryTwo_simplex boundary_simplex chainBasis chainBasis_apply chainBasis_coe chainBasis_repr chainClass chainClass_boundary chainClass_eq_iff chainLift chainLift_simplex chainMap_ext chainsEquivFinsupp chainsFromFinsupp chainsFromFinsupp_comp_repr chainsFromFinsupp_single chainsRepr chainsRepr_comp_fromFinsupp chainsRepr_simplex concatChain concatSimplex concatSimplex_apply concatSimplex_face_one concatSimplex_face_two concatSimplex_face_zero concatTime constantEdgeChain constantTriangleChain correctedHomotopyChain cycleClass cycleClass_surjective cycleVal cycles1Module cycles1_boundary homologyDesc homologyDescOfChain homologyDescOfChain_cycleClass homologyDesc_cycleClass homologyToChainClass homologyToChainClass_cycleClass homologyToChainClass_injective homotopyChain homotopyDiagonalSimplex homotopyLowerSimplex homotopyLowerSimplex_face_one homotopyLowerSimplex_face_two homotopyLowerSimplex_face_zero homotopyUpperSimplex homotopyUpperSimplex_face_one homotopyUpperSimplex_face_two homotopyUpperSimplex_face_zero inducedChain inducedChain_boundary inducedChain_comp inducedChain_id inducedChain_simplex inducedCycles inducedCycles_val inducedHomology inducedHomology_comp inducedHomology_cycleClass inducedHomology_id lowerTriangleMap lowerTriangle_face_one lowerTriangle_face_two lowerTriangle_face_zero mem_simplex_span_iff mkCycle1 opchainsModule pathChain pathChain_refl pathSimplex pathSimplex_face_one pathSimplex_face_zero pathSimplex_simplexPath pathSimplex_vertex_one pathSimplex_vertex_zero pointChain simplexChain simplexChain_span simplexCoordinate simplexFace simplexFace_apply simplexFace_apply_self simplexFace_apply_succAbove simplexFace_one_one simplexFace_one_two simplexFace_one_zero simplexFace_zero_one simplexFace_zero_zero simplexIndex simplexIndex_face simplexPath simplexZero_eq_vertex simplex_span_inter singularChainMap singularComplex upperTriangleMap upperTriangle_face_one upperTriangle_face_two upperTriangle_face_zero)
export SingularChains (simplexFace_vertex simplex_contractible simplex_simplyConnected triangleFacePath triangleEdge01 triangleEdge12 triangleEdge02 triangleEdges_homotopic)
end FirstHurewicz

export SingularHomology (CircleTopology.Circle CircleTopology.arcU CircleTopology.arcUContractible CircleTopology.arcUHomeomorph CircleTopology.arcUHomeomorph_coe CircleTopology.arcU_mem_arcV_iff CircleTopology.arcU_open CircleTopology.arcV CircleTopology.arcVContractible CircleTopology.arcVHomeomorph CircleTopology.arcVHomeomorph_coe CircleTopology.arcV_open CircleTopology.arc_cover CircleTopology.circleLiftContraction CircleTopology.circleProductLiftContraction CircleTopology.contractibleProdHomotopyEquiv CircleTopology.contractionPoint CircleTopology.contractionPoint_homotopic CircleTopology.foldMap CircleTopology.halfPoint CircleTopology.halfPoint_ne_zero CircleTopology.intersectionHomeomorph CircleTopology.intersectionPuncturedHomeomorph CircleTopology.intersectionSubtypeHomeomorph CircleTopology.intervalContractible CircleTopology.leftIntervalContractible CircleTopology.mem_arcU CircleTopology.mem_arcV CircleTopology.productArcHomeomorph CircleTopology.productIntersectionArcHomeomorph CircleTopology.productIntersectionHomeomorph CircleTopology.productIntersectionHomotopyEquiv CircleTopology.productIntersectionHomotopyEquiv_fold CircleTopology.productIntersectionToU CircleTopology.productIntersectionToU_fold CircleTopology.productIntersectionToV CircleTopology.productIntersectionToV_fold CircleTopology.productProjection CircleTopology.productProjection_comp_productSection CircleTopology.productSection CircleTopology.productU CircleTopology.productUCoordinate CircleTopology.productUCoordinate_coe CircleTopology.productUHomeomorph CircleTopology.productUHomotopyEquiv CircleTopology.productUInclusion CircleTopology.productUInclusionHomotopy CircleTopology.productU_open CircleTopology.productV CircleTopology.productVCoordinate CircleTopology.productVCoordinate_coe CircleTopology.productVHomeomorph CircleTopology.productVHomotopyEquiv CircleTopology.productVInclusion CircleTopology.productVInclusionHomotopy CircleTopology.productV_open CircleTopology.product_cover CircleTopology.puncturedCircleHomeomorph CircleTopology.puncturedIntervalHomeomorph CircleTopology.puncturedIntervalInl CircleTopology.puncturedIntervalInl_continuous CircleTopology.puncturedIntervalInl_isOpenMap CircleTopology.puncturedIntervalInr CircleTopology.puncturedIntervalInr_continuous CircleTopology.puncturedIntervalInr_isOpenMap CircleTopology.puncturedIntervalSumEquiv CircleTopology.rightIntervalContractible CircleTopology.sumContinuousMap CircleTopology.sumHomotopy CircleTopology.sumHomotopyEquiv circleBoundary circleBoundaryCoordinates circleBoundaryCoordinates_ker circleBoundaryCoordinates_range circleBoundary_apply circleBoundary_exact circleBoundary_negativeFirst_ker circleBoundary_negativeFirst_surjective circleBoundary_sum_eq_zero circleBoundary_surjective circleHomologyOneEquiv circleHomologyOneEquiv_apply circleMayerVietorisConnecting circleProductHomologyEquiv circleProductHomologyEquiv_apply circleProductHomologyEquiv_section circleProductHomologyZeroEquiv circleProductLeftHomologyMap_apply circleProductRightHomologyMap_apply circleProductRightHomologyMap_range circleProjectionHomology circleProjection_section circleSectionHomology circleSectionHomology_zero_surjective circleSplitExactEquiv circleSplitExactEquiv_apply_inclusion circle_homology_subsingleton connectedHomologyZeroEquiv connectedHomologyZeroEquiv_natural connectedHomologyZeroEquiv_pointClass connectingHomomorphism_cycleClass connectingMap_cycleClass contractibleHomologyEquivPoint contractible_homology_subsingleton disjointHomology_id_apply eq_zsmul_pointClass homeomorphHomologyEquiv homeomorphHomologyEquiv_apply homeomorphHomologyEquiv_refl homeomorphHomologyEquiv_symm homeomorphHomologyEquiv_symm_apply homeomorphHomologyEquiv_toLinearMap homeomorphHomologyEquiv_trans homotopic_homologyMap homotopyEquivHomologyEquiv homotopyEquivHomologyEquiv_apply homotopyEquivHomologyEquiv_symm_apply homotopyEquivHomologyEquiv_toLinearMap homotopyInverseHomologyEquiv homotopy_homologyMap intLinearMapOfAddHom mapCycles_pointCycle negativeFirstMap pairSumMap pairSumMap_apply pointClass pointClass_augmentation pointClass_eq_pointCycleLift pointCycle pointCycleLift pointCycle_val pointHomologyZeroEquiv point_homology_subsingleton productArcHomologyEquiv productFold_homology productIntersectionHomologyEquiv productIntersectionHomologyEquiv_apply productIntersectionToU_homology productIntersectionToV_homology productUInclusion_homology productVInclusion_homology singularChainHomotopy singularHomologyMap_comp singularHomologyMap_id singularHomologyMap_pointClass singularSimplex_sum_split smallConnectingMap_cycleClass splitExactEquiv splitExactEquiv_apply splitExactEquiv_apply_inclusion splitExactPair_injective splitExactPair_surjective sumChainComplexIso sumChainComplexMap sumChainComplexMap_comp_inverse sumChainComplexMap_component_isIso sumChainInverseDegree_inl sumChainInverseDegree_inr sumChainInverseDegree sumChainInverse_comp_map sumElimMap sumElim_homology_inl sumElim_homology_inr sumHomologyEquiv sumHomologyEquiv_fold sumHomologyEquiv_inl sumHomologyEquiv_inr sumHomologyEquiv_sumElim sumHomologyEquiv_sumElim_symm sumHomologyEquiv_symm_apply sumInlMap sumInrMap sumSimplexEquiv sumSimplexEquiv_symm_inl sumSimplexEquiv_symm_inr sumSimplexMap sumSimplexMap_injective sumSimplexMap_surjective totallyDisconnected_homology_isZero totallyDisconnected_homology_subsingleton trivialFirstEquiv)
namespace PeriodTorusHigherHomology
export SingularHomology (CircleTopology.Circle CircleTopology.arcU CircleTopology.arcUContractible CircleTopology.arcUHomeomorph CircleTopology.arcUHomeomorph_coe CircleTopology.arcU_mem_arcV_iff CircleTopology.arcU_open CircleTopology.arcV CircleTopology.arcVContractible CircleTopology.arcVHomeomorph CircleTopology.arcVHomeomorph_coe CircleTopology.arcV_open CircleTopology.arc_cover CircleTopology.circleLiftContraction CircleTopology.circleProductLiftContraction CircleTopology.contractibleProdHomotopyEquiv CircleTopology.contractionPoint CircleTopology.contractionPoint_homotopic CircleTopology.foldMap CircleTopology.halfPoint CircleTopology.halfPoint_ne_zero CircleTopology.intersectionHomeomorph CircleTopology.intersectionPuncturedHomeomorph CircleTopology.intersectionSubtypeHomeomorph CircleTopology.intervalContractible CircleTopology.leftIntervalContractible CircleTopology.mem_arcU CircleTopology.mem_arcV CircleTopology.productArcHomeomorph CircleTopology.productIntersectionArcHomeomorph CircleTopology.productIntersectionHomeomorph CircleTopology.productIntersectionHomotopyEquiv CircleTopology.productIntersectionHomotopyEquiv_fold CircleTopology.productIntersectionToU CircleTopology.productIntersectionToU_fold CircleTopology.productIntersectionToV CircleTopology.productIntersectionToV_fold CircleTopology.productProjection CircleTopology.productProjection_comp_productSection CircleTopology.productSection CircleTopology.productU CircleTopology.productUCoordinate CircleTopology.productUCoordinate_coe CircleTopology.productUHomeomorph CircleTopology.productUHomotopyEquiv CircleTopology.productUInclusion CircleTopology.productUInclusionHomotopy CircleTopology.productU_open CircleTopology.productV CircleTopology.productVCoordinate CircleTopology.productVCoordinate_coe CircleTopology.productVHomeomorph CircleTopology.productVHomotopyEquiv CircleTopology.productVInclusion CircleTopology.productVInclusionHomotopy CircleTopology.productV_open CircleTopology.product_cover CircleTopology.puncturedCircleHomeomorph CircleTopology.puncturedIntervalHomeomorph CircleTopology.puncturedIntervalInl CircleTopology.puncturedIntervalInl_continuous CircleTopology.puncturedIntervalInl_isOpenMap CircleTopology.puncturedIntervalInr CircleTopology.puncturedIntervalInr_continuous CircleTopology.puncturedIntervalInr_isOpenMap CircleTopology.puncturedIntervalSumEquiv CircleTopology.rightIntervalContractible CircleTopology.sumContinuousMap CircleTopology.sumHomotopy CircleTopology.sumHomotopyEquiv circleBoundary circleBoundaryCoordinates circleBoundaryCoordinates_ker circleBoundaryCoordinates_range circleBoundary_apply circleBoundary_exact circleBoundary_negativeFirst_ker circleBoundary_negativeFirst_surjective circleBoundary_sum_eq_zero circleBoundary_surjective circleHomologyOneEquiv circleHomologyOneEquiv_apply circleMayerVietorisConnecting circleProductHomologyEquiv circleProductHomologyEquiv_apply circleProductHomologyEquiv_section circleProductHomologyZeroEquiv circleProductLeftHomologyMap_apply circleProductRightHomologyMap_apply circleProductRightHomologyMap_range circleProjectionHomology circleProjection_section circleSectionHomology circleSectionHomology_zero_surjective circleSplitExactEquiv circleSplitExactEquiv_apply_inclusion circle_homology_subsingleton connectedHomologyZeroEquiv connectedHomologyZeroEquiv_natural connectedHomologyZeroEquiv_pointClass connectingHomomorphism_cycleClass connectingMap_cycleClass contractibleHomologyEquivPoint contractible_homology_subsingleton disjointHomology_id_apply eq_zsmul_pointClass homeomorphHomologyEquiv homeomorphHomologyEquiv_apply homeomorphHomologyEquiv_refl homeomorphHomologyEquiv_symm homeomorphHomologyEquiv_symm_apply homeomorphHomologyEquiv_toLinearMap homeomorphHomologyEquiv_trans homotopic_homologyMap homotopyEquivHomologyEquiv homotopyEquivHomologyEquiv_apply homotopyEquivHomologyEquiv_symm_apply homotopyEquivHomologyEquiv_toLinearMap homotopyInverseHomologyEquiv homotopy_homologyMap intLinearMapOfAddHom mapCycles_pointCycle negativeFirstMap pairSumMap pairSumMap_apply pointClass pointClass_augmentation pointClass_eq_pointCycleLift pointCycle pointCycleLift pointCycle_val pointHomologyZeroEquiv point_homology_subsingleton productArcHomologyEquiv productFold_homology productIntersectionHomologyEquiv productIntersectionHomologyEquiv_apply productIntersectionToU_homology productIntersectionToV_homology productUInclusion_homology productVInclusion_homology singularChainHomotopy singularHomologyMap_comp singularHomologyMap_id singularHomologyMap_pointClass singularSimplex_sum_split smallConnectingMap_cycleClass splitExactEquiv splitExactEquiv_apply splitExactEquiv_apply_inclusion splitExactPair_injective splitExactPair_surjective sumChainComplexIso sumChainComplexMap sumChainComplexMap_comp_inverse sumChainComplexMap_component_isIso sumChainInverseDegree_inl sumChainInverseDegree_inr sumChainInverseDegree sumChainInverse_comp_map sumElimMap sumElim_homology_inl sumElim_homology_inr sumHomologyEquiv sumHomologyEquiv_fold sumHomologyEquiv_inl sumHomologyEquiv_inr sumHomologyEquiv_sumElim sumHomologyEquiv_sumElim_symm sumHomologyEquiv_symm_apply sumInlMap sumInrMap sumSimplexEquiv sumSimplexEquiv_symm_inl sumSimplexEquiv_symm_inr sumSimplexMap sumSimplexMap_injective sumSimplexMap_surjective totallyDisconnected_homology_isZero totallyDisconnected_homology_subsingleton trivialFirstEquiv)
end PeriodTorusHigherHomology

namespace Suspension
abbrev instLocal1 := @instTopologicalSpace
abbrev topSus := @Suspension
namespace topSus
export Suspension (NorthCylinder SouthCylinder continuous_height continuous_mk continuous_realHeight height isQuotientMap_mk joined_north liftFromSurjection_comp liftFromSurjection_continuous liftFromSurjection mem_northOpen mem_southOpen middleBand middleBandHomeomorph middleBandHomotopyEquiv middleBandHomotopyEquiv_apply middleBandQuotientHomeomorph middleBand_isOpen middleBand_restrict_injective middleCylinder middleCylinderHomeomorph middleCylinder_height middleInterval_contractibleSpace mk mk_eq_mk_iff mk_one mk_one_eq mk_surjective mk_zero mk_zero_eq north northContract_continuous northContract northContract_projection northContraction northCylinderContraction_continuous northCylinderContraction northCylinderContraction_respects northOpen northOpen_contractibleSpace northOpen_isOpen northProjection_isQuotientMap northProjection north_mem_northOpen open_cover south southContract_continuous southContract southContract_projection southContraction southCylinderContraction_continuous southCylinderContraction southCylinderContraction_respects southOpen southOpen_contractibleSpace southOpen_isOpen southProjection_isQuotientMap southProjection south_mem_southOpen suspension_compactSpace suspension_pathConnectedSpace)
abbrev instLocal1 := @Suspension.instNonempty
end topSus
end Suspension

export Suspension (topSus topSus.NorthCylinder topSus.SouthCylinder topSus.continuous_height topSus.continuous_mk topSus.continuous_realHeight topSus.height topSus.instLocal1 topSus.isQuotientMap_mk topSus.joined_north topSus.liftFromSurjection_comp topSus.liftFromSurjection_continuous topSus.liftFromSurjection topSus.mem_northOpen topSus.mem_southOpen topSus.middleBand topSus.middleBandHomeomorph topSus.middleBandHomotopyEquiv topSus.middleBandHomotopyEquiv_apply topSus.middleBandQuotientHomeomorph topSus.middleBand_isOpen topSus.middleBand_restrict_injective topSus.middleCylinder topSus.middleCylinderHomeomorph topSus.middleCylinder_height topSus.middleInterval_contractibleSpace topSus.mk topSus.mk_eq_mk_iff topSus.mk_one topSus.mk_one_eq topSus.mk_surjective topSus.mk_zero topSus.mk_zero_eq topSus.north topSus.northContract_continuous topSus.northContract topSus.northContract_projection topSus.northContraction topSus.northCylinderContraction_continuous topSus.northCylinderContraction topSus.northCylinderContraction_respects topSus.northOpen topSus.northOpen_contractibleSpace topSus.northOpen_isOpen topSus.northProjection_isQuotientMap topSus.northProjection topSus.north_mem_northOpen topSus.open_cover topSus.south topSus.southContract_continuous topSus.southContract topSus.southContract_projection topSus.southContraction topSus.southCylinderContraction_continuous topSus.southCylinderContraction topSus.southCylinderContraction_respects topSus.southOpen topSus.southOpen_contractibleSpace topSus.southOpen_isOpen topSus.southProjection_isQuotientMap topSus.southProjection topSus.south_mem_southOpen topSus.suspension_compactSpace topSus.suspension_pathConnectedSpace contractibleCoverConnectingToKernel contractibleCoverConnectingToKernel_bijective contractibleCoverConnecting_injective contractibleCoverConnecting_surjective contractibleCoverHomologyHigherEquiv contractibleCoverHomologyOneEquivKernel instLocal1 singularHomologyMap_const_eq_zero singularHomologyMap_eq_zero_of_nullhomotopic suspensionSetoid)
namespace CuspCentralHomology
abbrev Suspension {X : Type*} [TopologicalSpace X] := Suspension.topSus X
export Suspension (topSus topSus.NorthCylinder topSus.SouthCylinder topSus.continuous_height topSus.continuous_mk topSus.continuous_realHeight topSus.height topSus.instLocal1 topSus.isQuotientMap_mk topSus.joined_north topSus.liftFromSurjection_comp topSus.liftFromSurjection_continuous topSus.liftFromSurjection topSus.mem_northOpen topSus.mem_southOpen topSus.middleBand topSus.middleBandHomeomorph topSus.middleBandHomotopyEquiv topSus.middleBandHomotopyEquiv_apply topSus.middleBandQuotientHomeomorph topSus.middleBand_isOpen topSus.middleBand_restrict_injective topSus.middleCylinder topSus.middleCylinderHomeomorph topSus.middleCylinder_height topSus.middleInterval_contractibleSpace topSus.mk topSus.mk_eq_mk_iff topSus.mk_one topSus.mk_one_eq topSus.mk_surjective topSus.mk_zero topSus.mk_zero_eq topSus.north topSus.northContract_continuous topSus.northContract topSus.northContract_projection topSus.northContraction topSus.northCylinderContraction_continuous topSus.northCylinderContraction topSus.northCylinderContraction_respects topSus.northOpen topSus.northOpen_contractibleSpace topSus.northOpen_isOpen topSus.northProjection_isQuotientMap topSus.northProjection topSus.north_mem_northOpen topSus.open_cover topSus.south topSus.southContract_continuous topSus.southContract topSus.southContract_projection topSus.southContraction topSus.southCylinderContraction_continuous topSus.southCylinderContraction topSus.southCylinderContraction_respects topSus.southOpen topSus.southOpen_contractibleSpace topSus.southOpen_isOpen topSus.southProjection_isQuotientMap topSus.southProjection topSus.south_mem_southOpen topSus.suspension_compactSpace topSus.suspension_pathConnectedSpace contractibleCoverConnectingToKernel contractibleCoverConnectingToKernel_bijective contractibleCoverConnecting_injective contractibleCoverConnecting_surjective contractibleCoverHomologyHigherEquiv contractibleCoverHomologyOneEquivKernel instLocal1 singularHomologyMap_const_eq_zero singularHomologyMap_eq_zero_of_nullhomotopic suspensionSetoid)
end CuspCentralHomology

export Coproduct (homologyBiproductEquiv homologyBiproductEquiv_desc homologyBiproductEquiv_symm_apply homologyFiniteBiproducts homology_biproduct_total homology_π_ι_ne homology_π_ι_self sigmaChainComplexInverse sigmaChainComplexInverse_comp_map sigmaChainComplexInverse_inclusion sigmaChainComplexIso sigmaChainComplexMap sigmaChainComplexMap_comp_inverse sigmaChainComplexMap_inclusion sigmaChainInverseDegree_comp_inclusion sigmaChainInverseDegree_inclusion sigmaChainInverseDegree sigmaChains_hom_ext sigmaHomologyEquiv sigmaHomologyEquiv_symm_apply sigmaHomologyEquiv_symm_single sigmaInclusion sigmaSimplexEquiv sigmaSimplexEquiv_symm_inclusion sigmaSimplexMap sigmaSimplexMap_injective sigmaSimplexMap_surjective singularChainsFiniteBiproducts singularSimplex_sigma_split)
namespace ThreefoldHomologyStarCoproduct
export Coproduct (homologyBiproductEquiv homologyBiproductEquiv_desc homologyBiproductEquiv_symm_apply homologyFiniteBiproducts homology_biproduct_total homology_π_ι_ne homology_π_ι_self sigmaChainComplexInverse sigmaChainComplexInverse_comp_map sigmaChainComplexInverse_inclusion sigmaChainComplexIso sigmaChainComplexMap sigmaChainComplexMap_comp_inverse sigmaChainComplexMap_inclusion sigmaChainInverseDegree_comp_inclusion sigmaChainInverseDegree_inclusion sigmaChainInverseDegree sigmaChains_hom_ext sigmaHomologyEquiv sigmaHomologyEquiv_symm_apply sigmaHomologyEquiv_symm_single sigmaInclusion sigmaSimplexEquiv sigmaSimplexEquiv_symm_inclusion sigmaSimplexMap sigmaSimplexMap_injective sigmaSimplexMap_surjective singularChainsFiniteBiproducts singularSimplex_sigma_split)
end ThreefoldHomologyStarCoproduct

export OnePointCollapse (collapse collapseMap collapse_coe collapse_eq_iff collapse_eq_infty_iff collapse_of_mem collapse_of_not_mem collapse_preimage_compl_of_mem collapse_preimage_of_not_mem collapse_surjective continuous_collapse isQuotientMap_collapse collapseLift collapseLift_comp collapseLift_apply)
namespace SixSphereCube
export OnePointCollapse (collapse collapseMap collapse_coe collapse_eq_iff collapse_eq_infty_iff collapse_of_mem collapse_of_not_mem collapse_preimage_compl_of_mem collapse_preimage_of_not_mem collapse_surjective continuous_collapse isQuotientMap_collapse collapseLift collapseLift_comp collapseLift_apply)
end SixSphereCube

namespace PeriodTorusHigherHomology
export SingularHomology (crossInsertLeft crossInsertLeft_natural inducedChain_crossInsertLeft)
end PeriodTorusHigherHomology
namespace FirstHurewicz
export SingularChains (AbelianPi1 abelianPi1EquivOfPi1 abelianPi1EquivOfPi1_of basePathChain basePathChain_pointChain basedLoop basedLoopClass basedLoopClass_cast basedLoopClass_eq basedLoopClass_homotopic basedLoopClass_loop basedLoopClass_simplexPath_pathSimplex basedLoopClass_trans basedLoopClass_triangle basedLoopClass_triangle_boundary basedLoopQuotient basedLoopQuotient_trans basedLoop_homotopic edgeClosure_chain_identity edgeClosure_cycle edgeClosure_pathChain edgeLoopCochain edgeLoopCochain_loopSimplex edgeLoopCochain_pathSimplex edgeLoopCochain_simplex homologyToChainClass_hurewiczMap_loopClass homologyToChainClass_loopHomologyClass hurewiczFunction hurewiczMap hurewiczMap_basedLoopClass hurewiczMap_loopClass hurewiczPi1 inducedCycles_loopCycle inducedHomology_loopHomologyClass loopClass loopClass_homotopic loopClass_surjective loopClass_symm loopClass_trans loopCycle loopCycle_val loopHomologyClass loopHomologyClass_homotopic loopHomologyClass_refl loopHomologyClass_trans loopQuotient loopQuotient_symm loopQuotient_trans pathClass pathClass_cast pathClass_homotopic pathClass_homotopy pathClass_refl pathClass_symm pathClass_trans pathSimplex_map simplexPath_pathSimplex_cast inducedChain_pathChain)
end FirstHurewicz

namespace ThreefoldHomologyFinitenessRetraction
export SublevelRetraction (Positive Sublevel extendedHomotopy extension extensionFun extensionFun_apply_of_nonpos extensionFun_apply_of_pos extensionFun_apply_of_small extensionFun_continuous extensionFun_continuousOn_positive extensionFun_continuousOn_small extension_apply_of_nonpos extension_apply_of_pos extension_apply_of_small extension_one_lt extension_radius_le extension_stays_sublevel extension_zero restrictedHomotopy sublevelHomotopyEquiv sublevelInclusion sublevelMap)
end ThreefoldHomologyFinitenessRetraction

namespace CuspRetraction.Patching
abbrev LocalCollapse {X : Type*} [TopologicalSpace X] (f : C(X, ℝ)) := LocalCollapse.Collapse f
export LocalCollapse (Collapse exists_localCollapse_covering_zero exists_localCollapse_covering_zero_of_local exists_positive_sublevel_subset_open exists_small_sublevel_localCollapse zeroSet_isCompact)
end CuspRetraction.Patching

namespace FourthHurewicz.CubeSubdivision
export Hurewicz.CubeSubdivision (
  badPrism
  badPrism_le
  badPrism_le_ker
  badPrism_le_ker_orientedPrismRealization
  canonicalPrismDiscrepancy
  canonicalPrismDiscrepancy_mem_badPrism
  canonicalPrismDiscrepancy_succ
  canonicalPrismDiscrepancy_zero
  cubeAffineSimplex_comp
  cubeAffineSimplex_comp_selectedVertices
  evalLeft
  formalBoundary_firstFace_split_simplex
  formalCone_mem_badPrism
  formalEdgeCrossProduct_mem_badPrism_of_omit
  formalMap_prismDiscrepancy
  formalMap_standardPrism
  formalMap_succ_mem_badPrism
  lt_predAbove_iff_succAbove_lt
  mem_badPrism_of_left_zero
  mem_badPrism_of_omit
  orientedPrismRealization
  orientedPrismRealization_canonicalPrismDiscrepancy
  orientedPrismRealization_edge_eq_standard
  orientedPrismRealization_eq_sum
  orientedPrismRealization_interior_omitted
  orientedPrismRealization_last_omitted
  orientedPrismRealization_left_zero
  orientedPrismRealization_nonzero_omitted
  orientedPrismRealization_simplex
  orientedPrismRealization_standardPrism
  prismCubeMap
  prismCubeMap_affine
  prismCubeRealization
  prismCubeRealization_edgeCrossProduct
  prismCubeRealization_eq_induced
  prismCubeRealization_simplex
  prismCubeSimplex
  prismCubeSimplex_shuffle
  prismCubeSimplex_swap_of_omitted
  prismCubeSimplex_zero_of_last_omitted
  prismCubeSimplex_zero_of_left_zero
  prismCubeVertex
  prismCubeVertex_shuffle
  prismCubeVertex_succ
  prismCubeVertex_swap_of_ne
  prismDiscrepancy
  prismDiscrepancy_eq_map_canonical
  prismDiscrepancy_succ
  prismDiscrepancy_succ_retained
  prismDiscrepancy_zero
  retainedFirstBoundary
  retainedFirstBoundary_simplex
  shufflePrismVertices
  shufflePrismVertices_first
  shufflePrismVertices_map
  shufflePrismVertices_succ_index
  shufflePrismVertices_zero_index
  signed_sum_constant_eq_zero
  signed_sum_eq_zero_of_swap_invariant
  standardPrism
  standardPrism_succ
  standardPrism_zero
)
end FourthHurewicz.CubeSubdivision

namespace FourthHurewicz.CubeSubdivision.PermutationInsertion
export Hurewicz.CubeSubdivision.PermutationInsertion (
  insert
  insert_apply_self
  insert_apply_succAbove
  insert_bijective
  insert_injective
  insert_symm_apply_succ
  insert_symm_apply_zero
  sign_insert
  sign_insert_int
  sum_insert
  sum_sign_insert
  sum_sign_smul_insert
)
end FourthHurewicz.CubeSubdivision.PermutationInsertion

namespace HigherHurewicz
export Hurewicz (
  BasedSimplex
  NormalizationState
  TowerPair
  ambientSimplexCubeHomeomorph
  ambientSimplexCubeHomeomorph_image
  ambientSimplexCubeHomeomorph_image_frontier
  ambientSimplexCubeHomeomorph_mem_frontier_iff
  ambientSimplexCubeHomeomorph_mem_iff
  basedSimplexNativeLoop
  basedSimplexNativeLoop_comp_homeomorph
  basedSphereCube
  basedSphereCube_homologyClass
  boundarySignSum_even
  boundarySignSum_odd
  boundary_const_simplex
  boundary_constantSimplexChain
  boundary_constantSimplexChain_even
  boundary_constantSimplexChain_odd
  chainAugmentation_boundary
  chainAugmentation_boundary_even
  chainAugmentation_evenCycle
  chainLift_sub_constant_evenCycle
  classOperator
  classOperator_boundary
  classOperator_cubeChain
  classOperator_cubeChain_sum
  classOperator_simplex
  coherentCubeEndpoint_cell_boundary
  coherentCubeEndpoint_internalBased
  comp_singularHomologyDesc_eq_id
  composeSimplexHomotopies_one_straightening
  constantBasedSimplex
  constantSimplexChain
  constantSimplexChain_cycle_condition
  constantSimplexCycle
  constantSimplexCycle_class
  constantSimplexCycle_val
  continuous_flatSimplex
  continuous_simplexFlat
  convex_flatSimplexSet
  convex_realCubeSet
  correctedSimplexChain
  correctedSimplexChain_boundary
  correctedSimplexCycle
  correctedSimplexCycle_val
  cubeChain
  cubeChain_basedSimplexLoop
  cubeChain_boundary
  cubeChain_eq_squareChain
  cubeChain_eq_sum_simplices
  cubeChain_eq_sum_simplices_step
  cubeChain_one
  cubeChain_succ
  cubeChain_transAt_zero_diff
  cubeChain_transAt_zero_diff_boundary
  cubeChain_transAt_zero_extra_boundary
  cubeChain_transAt_zero_extra_eq_smul
  cubeChain_transAt_zero_extra_zero
  cubeChain_two
  cubeCoordinates
  cubeCoordinates_boundary_left
  cubeCoordinates_boundary_right
  cubeCoordinates_comp_prismCubeMap
  cubeCoordinates_one_comp_eq_squareCoordinates
  cubeCoordinates_succ
  cubeCoordinates_zero
  cubeCycle
  cubeCycle_val
  cubeHomologyClass
  cubeHomologyClass_const
  cubeHomologyClass_eq_squareHomologyClass
  cubeHomologyClass_homotopic
  cubeHomologyClass_transAt
  cubeHomologyClass_transAt_two
  cubeHomologyClass_transAt_two_coord
  cubeHomologyClass_transAt_zero
  cubeMap
  cubeRemainingCoordinates
  cubeScaleLeft
  cubeScaleLeft_zero_comp_cubeCoordinates
  cubeScaleRight
  cubeScaleRight_zero_comp_cubeCoordinates
  cubeScale_zero_sum_fundamentalCubeChain
  cubeSimplex_coordinate_equality_boundary
  cubeSimplex_ordered_coordinate_equality_boundary
  curryLoop
  edgeTower
  edgeTower_high_const
  edgeTower_low_const
  edgeTower_two_verticesBased
  evalLeft_comp_curryLoop
  evalLeft_crossProductEdge_intervalChain_simplex
  exists_ambientSimplexCubeHomeomorph
  exists_basepoint_adjustment
  factorMap_basedSphereCube
  factorMap_homotopyRel
  factorMap_homotopy_apply
  flatCubeHomeomorph
  flatSimplex
  flatSimplexSet
  flatSimplexSet_subset_Icc
  flatSimplex_simplexFlat
  funUniqueSymm_pathSimplex_eq_cubeSimplex_one
  fundamentalCubeChain
  fundamentalCubeChain_boundary_supported
  fundamentalCubeChain_succ
  fundamentalCubeChain_two
  hurewiczFunction
  hurewiczInverse
  hurewiczInverse_comp_hurewiczMap
  hurewiczInverse_cycleClass
  hurewiczInverse_hurewiczMap
  hurewiczInverse_hurewiczMap_mk
  hurewiczLinearEquiv
  hurewiczLinearEquivOfTwoLE
  hurewiczMap
  hurewiczMap_classOperator_cycle
  hurewiczMap_comp_hurewiczInverse
  hurewiczMap_eq_second
  hurewiczMap_hurewiczInverse
  hurewiczMap_injective
  hurewiczMap_representative
  hurewiczPi
  hurewicz_basedSimplexClass
  interior_flatSimplexSet
  interior_flatSimplexSet_nonempty
  interior_realCubeSet_nonempty
  intervalChain_split
  intervalPathLeft
  intervalPathLeft_trans_intervalPathRight
  intervalPathRight
  intervalScaleLeft
  intervalScaleRight
  isClosed_flatSimplexSet
  isClosed_realCubeSet
  isCompact_flatSimplexSet
  isCompact_realCubeSet
  lowerSquareTriangle_eq_cubeSimplex_one
  mem_interior_realCubeSet
  nativeCubeNullHomotopy
  nativeCubeNullHomotopy_comp
  normalizationBaseTwo
  normalizationCubeHomotopy
  normalizationHomotopy
  normalizationHomotopy_endpoint
  normalizationHomotopy_zero
  normalizationStep
  normalizationTower
  normalizationTower_const
  normalizedCube
  normalizedCube_cell
  normalizedCube_internalBased
  normalizedCube_simplex
  normalizedCycleAssignment
  normalizedCycleAssignment_class
  normalizedCycleAssignment_evenCycle
  normalizedCycleAssignment_oddCycle
  normalizedCycleAssignment_simplex
  normalizedCycleAssignment_val
  normalizedCycleAssignment_val_endpoint
  normalizedSimplex
  normalizedSimplex_boundary_relation
  normalizedTopSimplex
  normalizedTopSimplex_class_face
  pi_subsingleton_of_homology_vanishing
  realCubeHomeomorph
  realCubeHomeomorph_mem_boundary_iff
  realCubeSet
  realCubeSet_mem_frontier_iff
  right_inverse_is_left_inverse
  simplexCubeHomeomorph
  simplexCubeHomeomorph_boundary_iff
  simplexCubeHomeomorph_symm_boundary_iff
  simplexEndpoint_boundary
  simplexEndpoint_face_constant
  simplexFlat
  simplexFlatHomeomorph
  simplexFlatHomeomorph_mem_frontier_iff
  simplexFlatHomeomorph_mem_interior_iff
  simplexFlat_flatSimplex
  simplexNullHomotopy
  simplexNullHomotopyUnnormalized
  simplexNullHomotopy_constant
  simplexNullHomotopy_constant_toContinuousMap
  simplexNullHomotopy_one
  simplexNullHomotopy_zero
  simplexStraighteningHomotopy
  simplexStraighteningHomotopy_boundary
  simplexStraighteningHomotopy_const
  simplexStraighteningHomotopy_face
  simplexStraighteningHomotopy_one
  simplexStraighteningHomotopy_zero
  simplex_coordinate_zero_of_tail_eq
  singularHomologyDesc
  singularHomologyDesc_cycleClass
  sphere_homotopicRel_of_topClass_eq
  sphere_homotopic_id_of_topClass
  sphere_pi_subsingleton_of_lt
  straightenedCycle
  straightenedCycle_boundary
  straightenedCycle_class
  straightenedCycle_val
  topNormalization
  topNormalization_endpoint
  topNormalization_endpoint_face
  topNormalization_zero
  topStorey
  topStorey_face
  topStorey_relBoundary
  topStorey_zero
  towerBelow
  towerBelow_nxt_eq
  transAt_comp_cubeScaleLeft
  transAt_comp_cubeScaleRight
  transAt_cubeCoordinates_of_mem_boundary
  upperSquareTriangle_eq_cubeSimplex_swap
  vertexEdgeHomotopy
  vertexEdgeHomotopy_const
  vertexEdgeHomotopy_endpoint_boundary
  vertexEdgeHomotopy_face
  vertexEdgeHomotopy_one_endpoint
  vertexEdgeHomotopy_two_endpoint_boundary
  vertexEdgeHomotopy_zero
)
end HigherHurewicz

namespace HigherHurewicz.CubeGluing
export Hurewicz.CubeGluing (
  CubeCompatible
  coherentCubeCell_boundary
  coherentCubeCell_face
  coherentCubeCell_swap
  coherentCubeEndpoint
  coherentCubeEndpoint_cell
  coherentCubeFamily_compatible
  coherentCubeHomotopy
  coherentCubeHomotopyMap
  coherentCubeHomotopyMap_boundary
  coherentCubeHomotopyMap_cell
  coherentCubeHomotopyMap_zero
  cubeFamilyMap
  cubeFamilyMap_factorsThrough
  cubeOriginal_face_last
  cubeOriginal_face_swap
  cubeOriginal_face_zero
  glueCubeHomotopies
  glueCubeHomotopies_cell
  glueCubeHomotopies_time
  glueCubeHomotopies_zero
)
end HigherHurewicz.CubeGluing

namespace HigherHurewicz.CubeTriangulation
export Hurewicz.CubeTriangulation (
  CubeN
  SortedCoordinates
  continuous_cubeBarycentric
  continuous_cubeCoordinate
  continuous_cubeExtendedCoordinates
  coordinate_swap_of_tie
  cubeAffineSimplex
  cubeAffineSimplex_constant_coordinate
  cubeAffineSimplex_coordinate
  cubeAffineSimplex_face
  cubeAffineSimplex_vertex
  cubeBarycentric
  cubeBarycentric_inner
  cubeBarycentric_last
  cubeBarycentric_nonneg
  cubeBarycentric_sum
  cubeBarycentric_tail
  cubeBarycentric_zero
  cubeCylinderCover
  cubeCylinderCover_isQuotientMap
  cubeCylinderCover_surjective
  cubeExtendedCoordinates
  cubeExtendedCoordinates_antitone
  cubeExtendedCoordinates_inner
  cubeExtendedCoordinates_last
  cubeExtendedCoordinates_le_one
  cubeExtendedCoordinates_nonneg
  cubeExtendedCoordinates_zero
  cubeOrderedRegion
  cubeOrientation
  cubeOrientation_refl
  cubeOrientation_sum
  cubeOrientation_swap
  cubeSimplex
  cubeSimplexCylinder
  cubeSimplexInverse
  cubeSimplexInverse_simplex
  cubeSimplex_adjacent_difference
  cubeSimplex_antitone
  cubeSimplex_coordinate
  cubeSimplex_coordinate_last
  cubeSimplex_coordinate_zero
  cubeSimplex_eq_of_sorted
  cubeSimplex_face_last_boundary
  cubeSimplex_face_last_coordinate
  cubeSimplex_face_swap
  cubeSimplex_face_zero_boundary
  cubeSimplex_face_zero_coordinate
  cubeSimplex_injective
  cubeSimplex_inverse
  cubeSimplex_mem_boundary_iff
  cubeSimplex_overlap_preimage
  cubeSimplex_simplexBoundary
  cubeSimplex_sorted
  cubeSimplex_tie
  cubeSimplex_tie_iff
  cubeVertex
  cubeVertex_swap_of_ne
  eq_of_sorted_adjacent
  eq_of_value_preserving_swaps
  eq_swap_of_sorted_tie
  exists_cubeSimplex
  exists_sortedPermutation
  sortedCoordinates_swap_of_tie
  sortedPermutation
  sortedPermutation_sorted
  sorted_values_eq
  sum_cubeOrientation_faces
  sum_face_trichotomy
  sum_fin_differences
  sum_fin_differences_tail
  valuePreservingPermutation_induction
)
end HigherHurewicz.CubeTriangulation

namespace HigherHurewicz.CubicalBoundary
export Hurewicz.CubicalBoundary (
  BasedCubicalCell
  CubicalEvaluator
  alternatingSign_smul_involution
  alternatingSum_dimension_reduction
  alternatingSum_head
  cubeFacet
  cubeFacet_apply_self
  cubeFacet_apply_succAbove
  cubeFacet_succ_cons
  cubicalBoundaryValue
  cubicalBoundaryValue_dimension_reduction
  cubicalBoundaryValue_eq_zero
  cubicalBoundaryValue_square
  cubicalFace
  cubicalFace_apply
  cubicalLowerFace
  cubicalUpperFace
  instCoeFun1
  nativeCubicalEvaluator
  squareCubicalFacesHomotopy
  squareCubicalFaces_homotopic
  squareFacet_one
  squareFacet_zero
  squareLowerRoute
  squareLowerRoute_of_le
  squareLowerRoute_of_not_le
  squareLowerRoute_one
  squareLowerRoute_transAt_apply
  squareLowerRoute_zero
  squareRoutesBlend
  squareRoutesBlend_endpoint_one
  squareRoutesBlend_endpoint_zero
  squareRoutesBlend_one
  squareRoutesBlend_zero
  squareUpperRoute
  squareUpperRoute_of_le
  squareUpperRoute_of_not_le
  squareUpperRoute_one
  squareUpperRoute_transAt_apply
  squareUpperRoute_zero
  uncurryHead_update_succ
  uncurryLoop
  uncurryLoopHomotopy
  uncurryLoop_apply
  uncurryLoop_const
  uncurryLoop_homotopic
  uncurryLoop_swap
  uncurryLoop_symmAt
  uncurryLoop_transAt
  uncurryTail_update_succ
  whiskerCorner_based
  whiskerFacetNormal_arm_based
  whiskerFacet_last_coordinates
  whiskerFacet_last_upper_apply
  whiskerFacet_last_upper_uncurry_apply
  whiskerFacet_reflected_rotated_face_apply
  whiskerFacet_rotate_coordinates
  whiskerFacet_rotated_face_apply
  whiskerFacet_symmAt_zero_apply
  whiskerFacet_transAt_zero_apply
  whiskerFacet_zero_coordinates
  whiskerFinishTrack
  whiskerMap
  whiskerMap_apply
  whiskerMap_based_of_prefix_last
  whiskerMap_based_of_two_prefix
  whiskerMap_codimTwo_based
  whiskerMap_concat
  whiskerMap_finish
  whiskerMap_first
  whiskerMap_last_zero
  whiskerMap_middle
  whiskerMap_start
  whiskerMiddleTrack
  whiskerStartTrack
  whiskerTrack
  whiskerTrack_boundary
  whiskerTrack_concat
  whiskeredCell
  whiskeredCell_apply
  whiskeredCell_face_last_upper
  whiskeredCell_face_normal
  whiskeredCell_last_upper_value
  whiskeredCell_lower_value
  whiskeredCell_upper_value
  whiskeredLoop
  whiskeredLoopMap
)
end HigherHurewicz.CubicalBoundary

namespace HigherHurewicz.CubicalBoundary.CubicalEvaluator
export Hurewicz.CubicalBoundary.CubicalEvaluator (
  map_constantClosingPaths
  map_cyclicClosingPaths
  map_finRotate
  map_permutation
  uncurry
  uncurry_apply
)
end HigherHurewicz.CubicalBoundary.CubicalEvaluator

namespace HigherHurewicz.NativeSubdivision
export Hurewicz.NativeSubdivision (
  CutBased
  CutIndependent
  NativeChamberChart
  NativeCube
  NativeCubeInternalBased
  NativeCubeSameFlat
  chamberCutIndex
  chamberCutIndex_ne_castLE
  chamberCutSequence
  chamberCutSequence_castSucc
  chamberCutSequence_last
  chamberCutSequence_succ
  chamberCuts_sum_rev
  chamberLower
  chamberLower_last
  chamberLower_of_rank
  chamberLower_zero_face
  chamberOldCoordinates
  chamberOldCoordinates_cubeRestriction
  chamberSuccAbove_val_cases
  chamberUpper
  chamberUpper_first
  chamberUpper_of_rank
  chamberUpper_one_face
  chamberUpper_succ_eq_lower_castSucc
  continuous_prefixProduct
  cubeRestriction
  cubeRestriction_apply
  cubeRestriction_update_outside
  cutBinaryWarp
  cutBinaryWarp_apply
  cutBinaryWarp_of_half_le
  cutBinaryWarp_of_half_lt
  cutBinaryWarp_of_le_half
  cutBinaryWarp_one
  cutBinaryWarp_zero
  deletePermutation
  deletePermutationOption
  deletePermutationOption_none
  deletePermutation_castSucc
  extendCubeMap
  extendCubeMap_castLE
  extendCubeMap_outside
  extendCubeMap_refl
  extendCubeMap_sameFlat
  extendCubeMap_update_outside
  extendCubeMap_zero
  extend_insertChamberMap
  extendedChamberCutSequence
  extendedChamberCutSequence_based
  extendedChamberCutSequence_castSucc
  extendedChamberCutSequence_independent
  extendedChamberCutSequence_last
  extendedChamberCutSequence_succ
  extendedChamberCutSequence_zero
  extendedChamberCut_slice_eq
  extendedChamberHomotopy
  extendedChamberLoop
  extendedChamberLoop_apply
  extendedChamberLoop_zero
  extendedChamberMap_based
  extendedChamberMap_sameFlat
  finiteCuts_class
  finiteCuts_homotopic
  insertChamberChart
  insertChamberMap
  insertChamberMap_apply_castSucc
  insertChamberMap_apply_last
  insertChamberMap_one_adjacent
  insertChamberMap_one_first
  insertChamberMap_zero_adjacent
  insertChamberMap_zero_last
  insertPermutation
  insertPermutationEquiv
  insertPermutation_apply_at
  insertPermutation_apply_succAbove
  insertPermutation_deletePermutation
  insertPermutation_pair_injective
  insertPermutation_symm_last
  nativeBasedCubeSimplex
  nativeClass
  nativeClass_chamber_eq_orientedSimplex
  nativeClass_commonOrderedDuffy
  nativeClass_commonOrderedSimplex
  nativeClass_const
  nativeClass_eq_sum_partialChambers
  nativeClass_eq_sum_simplices
  nativeClass_extendedChamber_eq
  nativeClass_extendedChamber_eq_sum_insertions
  nativeClass_homotopic
  nativeClass_quarterTurn
  nativeClass_symmAt
  nativeClass_transAt
  nativeCubeBlend
  nativeCubeBlendMap
  nativeCubeBlend_based
  nativeCubeBlend_one
  nativeCubeBlend_zero
  nativeCubeLinearHomotopy
  nativeCubeOrderedDuffyHomotopy
  nativeCubePair
  nativeCubePullbackLoop
  nativeCubeQuarterTurnHomotopy
  nativeCubeQuarterTurnHomotopyMap
  nativeCubeQuarterTurnHomotopyMap_boundary
  nativeCubeQuarterTurnHomotopyMap_one
  nativeCubeQuarterTurnHomotopyMap_zero
  nativeCubeQuarterTurnLoop
  nativeCubeQuarterTurnLoop_apply
  nativeCubeQuarterTurnLoop_eq_symmAt_permute
  nativeCubeSimplexQuotient
  nativeCubeSimplexQuotient_adjacent_of_one
  nativeCubeSimplexQuotient_based
  nativeCubeSimplexQuotient_coordinate
  nativeCubeSimplexQuotient_coordinate_eq_zero
  nativeCubeSimplexQuotient_coordinate_zero_of_one
  nativeCubeSimplex_based
  nativeCubeSubdivision_class
  nativeDuffyCube
  nativeDuffyCubeCanonical
  nativeDuffyCubeClass_eq_basedSimplexClass
  nativeDuffyCubeLoop
  nativeDuffyCubeSimplexHomotopy
  nativeDuffyCube_adjacent_of_one
  nativeDuffyCube_apply
  nativeDuffyCube_based
  nativeDuffyCube_boundary
  nativeDuffyCube_coordinate
  nativeDuffyCube_coordinate_eq_zero
  nativeDuffyCube_coordinate_zero_of_one
  nativeDuffyCube_homotopic_basedSimplexLoop
  nativeDuffyCube_simplex_sameFlat
  nativeOrderedDuffyMap
  nativeOrderedDuffyMap_based
  nativeOrderedDuffyMap_coordinate
  nativeOrderedDuffyMap_coordinate_eq_zero
  nativeOrderedDuffyMap_one_adjacent
  nativeOrderedDuffyMap_one_first
  nativeOrderedDuffyMap_zero_adjacent
  nativeOrderedDuffyMap_zero_last
  optionCongr_removeNone_of_none
  orderedDuffyChart
  permuteCubeCoordinates
  permuteCubeCoordinates_boundary
  permuteCubeLoop
  permuteCubeLoop_additiveClass
  permuteCubeLoop_apply
  permuteCubeLoop_mul
  permuteCubeLoop_one
  permuteCubeLoop_swap_additiveClass
  prefixProduct
  prefixProduct_eq_zero_of_coordinate
  prefixProduct_succ
  prefixProduct_succ_of_one
  prefixProduct_zero
  sliceBinaryCoordinate
  sliceBinaryCoordinate_one
  sliceBinaryCoordinate_zero
  sliceConcat
  sliceConcat_class
  sliceHomotopyOfCoordinate
  sliceLoop
  sliceLoop_apply
  sliceLoop_full
  sliceLoop_self
  sliceMap
  sliceMap_based
  sliceTrans_apply
  slice_homotopic_concat
  slice_homotopic_trans
  slice_toLoop_transAt
  slice_transAt_homotopic
  sum_insertPermutation
)
end HigherHurewicz.NativeSubdivision

namespace HigherHurewicz.NativeSubdivision.NativeChamberChart
export Hurewicz.NativeSubdivision.NativeChamberChart (
  commonOrderedDuffy
  ext
  sameFlat
)
end HigherHurewicz.NativeSubdivision.NativeChamberChart

namespace HigherHurewicz.SimplexGeometry
export Hurewicz.SimplexGeometry (
  BasedSimplex
  BasedSimplexBoundary
  basedSimplexBoundaryFace
  basedSimplexBoundary_evaluation
  basedSimplexBoundary_signed_relation
  basedSimplexClass
  basedSimplexClass_straightening
  basedSimplexClass_topStorey
  basedSimplexLoop
  basedSimplexLoop_cubeSimplex_other
  basedSimplexLoop_cubeSimplex_refl
  basedSimplexLoop_straighteningHomotopy
  basedSimplexLoop_topStoreyHomotopy
  basedSimplex_face
  basedSimplex_simplexChain_sum
  continuous_extendedMinimum
  continuous_prefixMinimum
  cubeSimplex_coordinate_inversion
  cubeSimplex_quotient_coordinate
  cubeSimplex_quotient_of_antitone
  extendedMinimum
  extendedMinimum_antitone
  extendedMinimum_cubeFacet_last_zero
  extendedMinimum_cubeFacet_one_le
  extendedMinimum_cubeFacet_one_succ
  extendedMinimum_last_succ
  extendedMinimum_of_le
  extendedMinimum_zero
  prefixMinimum
  prefixMinimum_antitone
  prefixMinimum_eq_zero_of_coordinate
  prefixMinimum_insertNth_last_le
  prefixMinimum_insertNth_le
  prefixMinimum_insertNth_one_le
  prefixMinimum_insertNth_one_succ
  prefixMinimum_insertNth_succ
  prefixMinimum_le_coordinate
  prefixMinimum_of_antitone
  prefixMinimum_succ
  prefixMinimum_zero
  simplexBoundaryCube
  simplexBoundaryCube_boundaryValue
  simplexBoundaryCube_lower_constant
  simplexBoundaryCube_lower_last
  simplexBoundaryCube_upper
  simplexFace_simplexBoundary
  simplexQuotient
  simplexQuotient_apply
  simplexQuotient_bottom_not_last_twoBoundary
  simplexQuotient_boundary
  simplexQuotient_boundary_of_coordinate_le
  simplexQuotient_boundary_of_one
  simplexQuotient_boundary_of_zero
  simplexQuotient_castSucc
  simplexQuotient_castSucc_eq_zero_of_earlier_zero
  simplexQuotient_castSucc_eq_zero_of_one
  simplexQuotient_codimTwo
  simplexQuotient_cubeFacet_last_zero_apply
  simplexQuotient_cubeFacet_one_apply
  simplexQuotient_cubeSimplex_boundary
  simplexQuotient_cubeSimplex_refl
  simplexQuotient_last
  simplexQuotient_last_eq_zero_of_zero
  simplexTwoBoundary
  straightenedBasedSimplex
  straighteningHomotopy_one_based
  topStoreySimplex
)
end HigherHurewicz.SimplexGeometry

namespace HigherHurewicz.SimplexGeometry.BasedSimplexBoundary
export Hurewicz.SimplexGeometry.BasedSimplexBoundary (
  ofFaces
)
end HigherHurewicz.SimplexGeometry.BasedSimplexBoundary

namespace HigherHurewicz.TowerPair
export Hurewicz.TowerPair (
  step
)
end HigherHurewicz.TowerPair

namespace PeriodTorusLineBundle.ChernCocycle
export SingularChains (
  simplexFace_comp
  singularSimplex_face_face
)
end PeriodTorusLineBundle.ChernCocycle

namespace SixSphereCube
export Hurewicz.CubeSphere (
  CubeInteriorN
  OpenUnitInterval
  cubeBoundary_eq_iUnion
  cubeInteriorCoordinates
  cubeInteriorEuclideanHomeomorph
  isClosed_cubeBoundaryN
  not_mem_cubeBoundary_iff
  openUnitIntervalAffineOrderIso
  openUnitIntervalHomeomorph
)
end SixSphereCube

namespace ThirdHurewicz
export Hurewicz (
  coherentFaceBoundaryHomotopy_const
  composeSimplexHomotopies
  composeSimplexHomotopies_const
  composeSimplexHomotopies_face
  composeSimplexHomotopies_one
  composeSimplexHomotopies_zero
  cylinderHomotopy
  extendCoherentSimplexHomotopy_const
  gluedBoundaryMap_constant_value
  homotopyTrans_compContinuousMap
  homotopyTrans_congr
  homotopyTrans_const
  simplexFamilyHomotopy
  timeSlice_composeSimplexHomotopies_one
)
end ThirdHurewicz
namespace SecondHurewicz.SimplyConnected
noncomputable abbrev hurewiczLinearEquiv := @Hurewicz.degreeTwoLinearEquiv
end SecondHurewicz.SimplyConnected

namespace PeriodTorusHigherHomology
export SingularHomology (
  affineSimplex_constant
  affineSimplex_stdVertices_image
  chainBilinearLift
  chainBilinearLift_simplex
  chainBilinearLift_simplex_left
  chainBilinearMap_ext
  crossInsertRight
  crossProductCycleClasses
  crossProductCycleClasses_boundary_left
  crossProductCycleClasses_boundary_right
  crossProductCycles
  crossProductCycles_pointCycle_right
  crossProductCycles_val
  crossProductEdge
  crossProductEdge_affineChainMap
  crossProductEdge_boundary
  crossProductEdge_boundary_affine
  crossProductEdge_boundary_of_left_cycle
  crossProductEdge_boundary_zero
  crossProductEdge_boundary_zero_affine
  crossProductEdge_cycle
  crossProductEdge_natural
  crossProductEdge_pointCycle_right
  crossProductEdge_simplex
  crossProductEdge_zero_eq_zeroRight
  crossProductEdge_zero_simplex_right
  crossProductHomology
  crossProductHomologyCycles
  crossProductHomologyCycles_boundary_left
  crossProductHomologyFixed
  crossProductHomologyFixed_cycleClass
  crossProductHomology_cycleClass
  crossProductHomology_pointClass_right
  crossProductTriangle
  crossProductTriangle_affineChainMap
  crossProductTriangle_boundary
  crossProductTriangle_boundary_affine
  crossProductTriangle_boundary_of_right_cycle
  crossProductTriangle_boundary_zero
  crossProductTriangle_boundary_zero_affine
  crossProductTriangle_natural
  crossProductTriangle_simplex
  crossProductZeroLeft
  crossProductZeroLeft_affineChainMap
  crossProductZeroLeft_natural
  crossProductZeroLeft_simplex
  crossProductZeroLeft_simplex_left
  crossProductZeroRight
  crossProductZeroRight_simplex
  crossProductZeroRight_simplex_right
  formalBilinearLift
  formalBilinearLift_simplex
  formalBoundary_edgeCrossProduct
  formalBoundary_edgeCrossProduct_zero
  formalBoundary_edge_simplex
  formalBoundary_pointCrossProduct
  formalBoundary_triangleCrossProduct
  formalBoundary_triangleCrossProduct_zero
  formalChains_bilinear_ext
  formalEdgeCrossProduct
  formalEdgeCrossProduct_mem_supported
  formalEdgeCrossProduct_simplex_succ
  formalEdgeCrossProduct_zero_simplex_right
  formalMap_edgeCrossProduct
  formalMap_pointCrossProduct
  formalMap_triangleCrossProduct
  formalPointCrossProduct
  formalPointCrossProduct_edge_boundary
  formalPointCrossProduct_mem_supported
  formalPointCrossProduct_simplex
  formalPointCrossProduct_simplex_left
  formalPointCrossProduct_zero_simplex_right
  formalTriangleCrossProduct
  formalTriangleCrossProduct_simplex_succ
  formalTriangleCrossProduct_zero_simplex_right
  homologyBoundaries
  homologyBoundaries_le_ker
  homologyDesc
  homologyDesc_cycleClass
  homologyLinearMap_ext
  inducedChain_productAffineChainMap
  integerBilinearFlip
  integerBilinearFlip_apply
  integerBilinearPostcompose
  integerBilinearPostcompose_apply
  integerBilinearPrecompose
  integerBilinearPrecompose_apply
  integerBilinearRightApply
  integerBilinearRightApply_apply
  integerFormalBilinearMap_ext
  integerLinearMapModule
  integerTensorModule
  prodMap_productAffineSimplex
  productAffineChainMap
  productAffineChainMap_boundary
  productAffineChainMap_simplex
  productAffineSimplex
  productAffineSimplex_face
  productAffineSimplex_point_left
  productAffineSimplex_point_right
  productAffineSimplex_vertex
  zeroSimplexValue
  zeroSimplexValue_comp
)
end PeriodTorusHigherHomology

/-! ### `SecondHurewicz` → `Hurewicz.DegreeTwo` rename compatibility

The degree-two Hurewicz declarations were renamed from `SecondHurewicz`
to `Hurewicz.DegreeTwo`. These exports preserve every captured public
name for `Hopf` consumers; the list was generated from the pre-rename Lean environment
(see `Lib/docs/C16-NAMES.md`). `export` is used where the old parent is a namespace;
generated names under declaration parents (equation lemmas, structure fields) use
`alias`. -/

namespace SecondHurewicz
export Hurewicz.DegreeTwo (
  BasedLoopSpace
  Remaining
  boundaryThree_suspensionTwo
  boundaryTwo_suspensionOne_of_cycle
  crossProductEdge_point_right
  crossProductTriangle_point_right
  crossProductTriangle_zero_eq_zeroRight
  evaluated_edge_endpoint_cancel
  evaluated_triangle_endpoint_cancel
  evaluation
  evaluation_comp_right_one
  evaluation_comp_right_zero
  evaluation_comp_toLoop
  evaluation_one
  evaluation_right_one_chain
  evaluation_right_zero_chain
  evaluation_zero
  fundamentalSquareChain
  hurewiczFunction
  hurewiczMap
  hurewiczMap_representative
  hurewiczPi2
  induced_intervalChain
  intervalChain
  intervalChain_boundary
  mapGenLoop
  mapGenLoop_const
  mapGenLoop_homotopic
  mapGenLoop_transAt
  mapGenLoop_val
  pathSquareClass
  pathSquareClass_homotopic
  pathSquareClass_homotopy
  pathSquareClass_refl
  pathSquareClass_trans
  pathSquareCycle
  pathSquareCycle_val
  pathSquare_concat_boundary
  pathSquare_homotopy_boundary
  productSquareChain
  productSquareChain_boundary
  squareChain
  squareChain_boundary
  squareCoordinates
  squareCoordinates_one
  squareCoordinates_zero
  squareCycle
  squareHomologyClass
  squareHomologyClass_const
  squareHomologyClass_eq_pathSquareClass
  squareHomologyClass_homotopic
  squareHomologyClass_transAt
  squareMap
  suspensionOne
  suspensionOne_apply
  suspensionOne_toLoop
  suspensionTwo
  suspensionTwo_apply
  toLoop_const
  toLoop_transAt
)
end SecondHurewicz

namespace SecondHurewicz.SimplyConnected
export Hurewicz.DegreeTwo.SimplyConnected (
  BasedTetrahedron
  BasedTriangle
  CofaceCompatible
  FaceCompatible
  FaceCompatibleHomotopies
  SimplexBoundary
  SubdivisionSameSide
  SubdivisionSquare
  VertexHomotopyData
  VerticesBased
  barycenterCoordinate
  barycenterCoordinate_pos
  basedEdgePath
  basedEdgePath_const
  basedTetrahedronFace
  basedTetrahedron_boundary_relation
  basedTetrahedron_pair_relation
  basedTetrahedron_signed_relation
  basedTriangleClass
  basedTriangleClass_cyclic
  basedTriangleCycle
  basedTriangleCycle_val
  basedTriangleLoop
  basedTriangleLoop_lower
  basedTriangleLoop_upper
  basedTrianglesHomotopy
  basedTrianglesHomotopy_of_faces
  basedTrianglesLoop
  basedTrianglesLoop_apply
  basedTrianglesLoop_class
  basedTrianglesLoop_diagonal
  basedTrianglesLoop_lower
  basedTrianglesLoop_upper
  bottomDenominator_le
  bottomInclusion
  bottomOrSide
  bottomProductDegenerate
  bottomProductDegenerate_snd
  card_mul_barycenterCoordinate
  chainAugmentation
  chainAugmentation_boundaryTwo
  chainAugmentation_simplex
  chainAugmentation_twoCycle
  chainLift_sub_constant
  chainLift_sub_constant_twoCycle
  chosenBasePath
  chosenBasePath_self
  chosenNullHomotopy
  chosenNullHomotopy_refl
  coherentFaceBoundaryHomotopy
  coherentFaceBoundaryHomotopy_face
  coherentFaceBoundaryHomotopy_zero
  comp_secondHomologyDesc_eq_id
  constantBasedTriangle
  continuous_cylinderDenominator
  continuous_minimumCoordinate
  continuous_retractedSimplex
  continuous_retractedTime
  coordinateDenominator_le
  crossPoint_left
  cubeBoundary_productBoundary
  cyclicBasedTriangle
  cyclicTriangleLoopHomotopy
  cyclicTriangleQuotient_blend_boundary
  cyclicTriangleQuotient_commonZero
  cylinderDenominator
  cylinderDenominator_eq_one_of_mem
  cylinderDenominator_half_le
  cylinderDenominator_le_one
  cylinderDenominator_ne_zero
  cylinderDenominator_pos
  cylinderRetraction
  cylinderRetraction_bottom
  cylinderRetraction_fix
  cylinderRetraction_side
  cylinderRetraction_val_of_mem
  edgeNullHomotopy
  edgeNullHomotopy_const
  edgeNullHomotopy_one
  edgeNullHomotopy_vertex_one
  edgeNullHomotopy_vertex_zero
  edgeNullHomotopy_zero
  edgeStraightenedTriangle
  edgeStraighteningHomotopy
  edgeStraighteningHomotopy_const
  edgeStraighteningHomotopy_face
  edgeStraighteningHomotopy_one
  edgeStraighteningHomotopy_vertex
  edgeStraighteningHomotopy_zero
  exists_coordinate_eq_minimum
  extendBoundaryHomotopy
  extendBoundaryHomotopy_bottom
  extendBoundaryHomotopy_boundary
  extendBoundaryHomotopy_face
  extendBoundaryHomotopy_side
  extendCoherentSimplexHomotopy
  extendCoherentSimplexHomotopy_face
  extendCoherentSimplexHomotopy_zero
  faceCompatible_of_cofaceCompatible
  faceCompatible_zero
  faceFamilyMap
  faceFamilyMap_factorsThrough
  glueFaceHomotopies
  glueFaceHomotopies_face
  glueFaceHomotopies_time
  glueFaceHomotopies_unique
  glueFaceHomotopies_zero
  gluedBoundaryMap
  gluedBoundaryMap_bottomInclusion
  gluedBoundaryMap_sideInclusion
  gluedTriangleHomotopy
  gluedTriangleHomotopyMap
  gluedTriangleHomotopyMap_boundary
  hurewiczInverse
  hurewiczInverse_comp_hurewiczMap
  hurewiczInverse_cycleClass
  hurewiczInverse_hurewiczMap
  hurewiczInverse_hurewiczMap_mk
  hurewiczMap_comp_hurewiczInverse
  hurewiczMap_comp_triangleClassOperator
  hurewiczMap_hurewiczInverse
  hurewiczMap_triangleClassOperator_twoCycle
  hurewiczPi2Equiv
  hurewicz_basedTriangleClass
  inducedChain_timeSlice
  isClosed_simplexBoundary
  leftProductDegenerate
  leftProductDegenerate_fst
  lowerProductTriangle
  lowerProductTriangle_fst
  lowerProductTriangle_snd
  lowerSquareTriangle
  lowerSquareTriangle_one
  lowerSquareTriangle_outerFace
  lowerSquareTriangle_quotient
  lowerSquareTriangle_verticesBased
  lowerSquareTriangle_zero
  minimumCoordinate
  minimumCoordinate_eq_zero_of_mem_boundary
  minimumCoordinate_le
  minimumCoordinate_nonneg
  nextFaceHomotopies_compatible
  normalizedTetrahedron
  normalizedTetrahedronMap
  normalizedTetrahedronMap_face
  normalizedTetrahedronMap_face_boundary
  normalizedTetrahedron_face
  normalizedTriangle
  normalizedTriangleCycleOperator
  normalizedTriangleCycleOperator_simplex
  normalizedTriangleCycleOperator_twoCycle
  normalizedTriangleCycleOperator_val
  normalizedTriangle_boundary_relation
  normalizedTriangle_of_verticesBased
  normalizedTwoChain
  normalizedTwoChain_eq
  normalizedTwoChain_simplex
  normalizedTwoCycle
  normalizedTwoCycle_class
  normalizedTwoCycle_val
  prismOperator
  prismOperator_apply
  prismOperator_boundary
  prismOperator_domain
  prismOperator_simplex
  productSquareChain_four_triangles
  quarterTurn
  quarterTurnHomotopyMap
  quarterTurnHomotopyMap_boundary
  quarterTurnHomotopyMap_one
  quarterTurnHomotopyMap_zero
  quarterTurn_apply
  quarterTurn_boundary
  retractedCoordinate_nonneg
  retractedCoordinate_numerator_nonneg
  retractedCoordinates_sum
  retractedSimplex
  retractedSimplex_eq_of_mem
  retractedTime
  retractedTime_eq_of_mem
  retractedTime_le_one
  retractedTime_nonneg
  retracted_mem_bottomOrSide
  rotatedSquareLoop
  rotatedSquareLoop_class
  rotatedSquareLoop_homotopy
  rotationBlend
  rotationBlend_continuous
  rotationBlend_ne_zero
  rotationBlend_one
  rotationBlend_zero
  rotationBlend_zero_vector
  rotationCentered
  rotationCentered_continuous
  rotationCentered_norm_boundary
  rotationCentered_norm_le
  rotationDenominator
  rotationDenominator_continuous
  rotationDenominator_pos
  rotationNormalized
  rotationNormalized_continuous
  rotationNormalized_norm_boundary
  rotationNormalized_norm_le
  rotationNormalized_one
  rotationNormalized_zero
  rotationUncenter
  rotationUncenter_boundary
  rotationUncenter_centered
  rotationUncenter_congr
  rotationUncenter_vector
  rotationVector
  rotationVector_norm
  secondHomologyDesc
  secondHomologyDesc_cycleClass
  sideDenominator_le
  sideInclusion
  simplexBoundary
  simplexBoundary_exists_face
  simplexCard_pos
  simplexEndpointOperator
  simplexEndpointOperator_boundary
  simplexEndpointOperator_simplex
  simplexEndpointOperator_zero
  simplexFaceBoundary
  simplexFaceCover
  simplexFaceCover_isQuotientMap
  simplexFaceCover_surjective
  simplexFaceCylinder
  simplexFaceInverse
  simplexFace_injective
  simplexFace_intersection
  simplexFace_inverse
  simplexFace_mem_boundary
  simplexFace_range
  simplexFace_triangleBoundary
  simplexFace_two_one
  simplexFace_two_three
  simplexFace_two_two
  simplexFace_two_zero
  simplexPrism
  simplexPrismOperator
  simplexPrismOperator_boundary
  simplexPrismOperator_simplex
  simplexPrism_boundary
  simplexVertex_exists_face
  squareAffineTriangle
  squareAffineTriangle_fst_coe
  squareAffineTriangle_snd_coe
  squareChain_basedTriangleLoop
  squareChain_two_triangles
  squareLowerNormalizationHomotopy
  squareLowerNormalization_outerFace
  squareMap_basedTriangleLoop
  squareMap_bottomProductDegenerate
  squareMap_leftProductDegenerate
  squareNormalizationHomotopy
  squareNormalizationTriangleHomotopy
  squareNormalization_class
  squareNormalization_diagonal
  squareNormalization_edge_face
  squareNormalization_homotopic
  squareNormalization_quotient
  squareNormalizedLowerTriangle
  squareNormalizedUpperTriangle
  squareTriangles_diagonal
  squareUpperNormalizationHomotopy
  squareUpperNormalization_outerFace
  stationarySimplexHomotopy
  straightenedTwoCycle
  straightenedTwoCycle_class
  subdivisionBlend
  subdivisionBlendMap
  subdivisionBlend_based
  subdivisionBlend_one
  subdivisionBlend_zero
  subdivisionLinearHomotopy
  subdivisionLowerBasedTriangle
  subdivisionLowerProductLoop
  subdivisionLowerProductMap
  subdivisionLowerProductMap_based
  subdivisionLowerProductTriangle_sides
  subdivisionLowerSquareTriangle_based
  subdivisionLowerTriangleHomotopy
  subdivisionLowerTriangleLoop
  subdivisionLowerTriangleLoop_eq_basedTriangleLoop
  subdivisionLowerTriangleMap
  subdivisionLowerTriangleMap_based
  subdivisionOnDiagonal
  subdivisionPullbackLoop
  subdivisionSquare_boundary_cases
  subdivisionSubMin
  subdivisionSubMin_one_left
  subdivisionSubMin_one_right
  subdivisionSubMin_zero_left
  subdivisionSubMin_zero_right
  subdivisionTriangle_coordinate_sum
  subdivisionUpperConeHomotopy
  subdivisionUpperConeLoop
  subdivisionUpperConeMap
  subdivisionUpperConeMap_based
  subdivisionUpperConeTriangle_sides
  subdivisionUpperNegativeBasedTriangle
  subdivisionUpperNegativeBasedTriangle_loop_apply
  subdivisionUpperNegativeLoop
  subdivisionUpperNegativeLoop_eq_basedTriangleLoop
  subdivisionUpperNegativeMap
  subdivisionUpperNegativeMap_based
  subdivisionUpperNegativeReversedLoop
  subdivisionUpperNegativeReversedLoop_eq_symmAt
  subdivisionUpperNegativeReversedMap
  subdivisionUpperNegativeReversedMap_based
  subdivisionUpperNegativeSquareTriangle_based
  subdivisionUpperOrientationHomotopy
  subdivisionUpperOrientation_additiveClass
  subdivisionUpperOrientation_class
  subdivisionUpperOrientation_homotopic
  subdivisionUpperOrientation_sides
  subdivisionUpperPositiveBasedTriangle
  subdivisionUpperPositiveBasedTriangle_class_eq_neg
  subdivisionUpperPositiveSquareTriangle
  subdivisionUpperPositiveSquareTriangle_based
  subdivisionUpperPositiveSquareTriangle_one
  subdivisionUpperPositiveSquareTriangle_zero
  subdivisionUpperProductCone_sides
  subdivisionUpperProductLoop
  subdivisionUpperProductMap
  subdivisionUpperProductMap_based
  subdivisionUpperTriangleHomotopy
  subdivisionUpperTriangleLoop
  subdivisionUpperTriangleLoop_eq_basedTriangleLoop
  subdivisionUpperTriangleMap
  subdivisionUpperTriangleMap_based
  subdivisionWarpCoordinate
  subdivisionWarpCoordinate_apply
  subdivisionWarpCoordinate_of_half_le
  subdivisionWarpCoordinate_of_half_lt
  subdivisionWarpCoordinate_of_le_half
  subdivisionWarpCoordinate_one
  subdivisionWarpCoordinate_zero
  subdivisionWarpHomotopy
  subdivisionWarpLoop
  subdivisionWarpLoop_eq_transAt
  subdivisionWarpMap
  subdivisionWarpMap_based
  subdivisionWarpMap_sides
  subdivision_additiveClass
  subdivision_basedTriangleClass_sub
  subdivision_basedTriangleClass_sum
  subdivision_class
  subdivision_eq_sub_of_eq_add
  subdivision_homotopic
  subdivision_toLoop_transAt
  subdivision_transAt_homotopic
  tetrahedronEdgeStraighteningHomotopy
  tetrahedronEdgeStraighteningHomotopy_face
  tetrahedronEdgeStraighteningHomotopy_zero
  tetrahedronFillingsHomotopy
  tetrahedronFillings_class
  tetrahedronFillings_homotopic
  tetrahedronLowerLoop_eq_face
  tetrahedronOneSkeleton
  tetrahedronQuadrilateralA
  tetrahedronQuadrilateralA_boundary
  tetrahedronQuadrilateralA_diagonal
  tetrahedronQuadrilateralA_lower
  tetrahedronQuadrilateralA_upper
  tetrahedronQuadrilateralB
  tetrahedronQuadrilateralLoop
  tetrahedronQuadrilateralLoop_diagonal
  tetrahedronQuadrilateral_perimeter
  tetrahedronQuarterIndex
  tetrahedronQuarterShift
  tetrahedronQuarterShift_face_one
  tetrahedronQuarterShift_face_three
  tetrahedronQuarterShift_index
  tetrahedronQuarterShift_oneSkeleton
  tetrahedronShiftedLowerLoop_eq_face
  tetrahedronShiftedQuadrilateralLoop
  tetrahedronShiftedQuadrilateralLoop_diagonal
  tetrahedronShiftedUpperLoop_eq_face
  tetrahedronSimplexBlend
  tetrahedronSimplexBlendMap
  tetrahedronSimplexBlend_one
  tetrahedronSimplexBlend_self
  tetrahedronSimplexBlend_zero
  tetrahedronSimplexBlend_zero_coordinate
  tetrahedronUpperLoop_eq_face
  timeSlice
  timeSlice_face
  triangleBoundary
  triangleClassOperator
  triangleClassOperator_boundary
  triangleClassOperator_simplex
  triangleClassOperator_squareChain
  triangleCubeQuotient
  triangleCubeQuotient_boundary
  triangleCyclicPermutation
  triangleCyclicPermutation_boundary
  triangleEdgeStraighteningHomotopy
  triangleEdgeStraighteningHomotopy_face
  triangleEdgeStraighteningHomotopy_one_boundary
  triangleEdgeStraighteningHomotopy_one_face
  triangleEdgeStraighteningHomotopy_zero
  triangleProperty_of_face
  triangleQuotient
  triangleQuotient_lowerProductTriangle
  triangleQuotient_one
  triangleQuotient_perimeter_of_le
  triangleQuotient_two
  triangleQuotient_upperProductTriangle_boundary
  triangleQuotient_zero
  upperProductTriangle
  upperProductTriangle_fst
  upperProductTriangle_snd
  upperSquareTriangle
  upperSquareTriangle_one
  upperSquareTriangle_outerFace
  upperSquareTriangle_quotient
  upperSquareTriangle_verticesBased
  upperSquareTriangle_zero
  vertexBoundaryHomotopy
  vertexBoundaryHomotopy_face
  vertexBoundaryHomotopy_zero
  vertexHomotopy
  vertexHomotopy_const
  vertexHomotopy_one
  vertexHomotopy_zero
  vertexInitialData
  vertexNormalizedSimplex
  vertexNormalizedSimplex_face
  vertexNormalizedSimplex_of_verticesBased
  vertexNormalizedSimplex_verticesBased
  vertexNormalizedTwoCycle
  vertexNormalizedTwoCycle_class
  vertexStepHomotopy
  vertexStepHomotopy_face
  vertexStepHomotopy_faceCompatible
  vertexStepHomotopy_face_apply
  vertexStepHomotopy_of_not_verticesBased
  vertexStepHomotopy_of_verticesBased
  vertexStepHomotopy_one_verticesBased
  vertexStepHomotopy_zero
  vertexStraighteningData
  vertexStraighteningHomotopy
  vertexStraighteningHomotopy_const
  vertexStraighteningHomotopy_face
  vertexStraighteningHomotopy_of_verticesBased
  vertexStraighteningHomotopy_one_verticesBased
  vertexStraighteningHomotopy_timeSlice_face
  vertexStraighteningHomotopy_timeSlice_of_verticesBased
  vertexStraighteningHomotopy_timeSlice_zero
  vertexStraighteningHomotopy_zero
  verticesBased_const
  verticesBased_zero_iff
)
end SecondHurewicz.SimplyConnected

namespace SecondHurewicz.SimplyConnected.BasedTetrahedron
export Hurewicz.DegreeTwo.SimplyConnected.BasedTetrahedron (
  ofFaces
)
end SecondHurewicz.SimplyConnected.BasedTetrahedron

namespace SecondHurewicz.SimplyConnected.SubdivisionSameSide
export Hurewicz.DegreeTwo.SimplyConnected.SubdivisionSameSide (
  casesOn
  diagonal
  one
  rec
  recOn
  zero
)
end SecondHurewicz.SimplyConnected.SubdivisionSameSide

namespace SecondHurewicz.SimplyConnected.VertexHomotopyData
export Hurewicz.DegreeTwo.SimplyConnected.VertexHomotopyData (
  casesOn
  ctorIdx
  face_compatible
  homotopy
  mk
  next
  noConfusion
  noConfusionType
  of_verticesBased
  one_verticesBased
  rec
  recOn
  zero
)
end SecondHurewicz.SimplyConnected.VertexHomotopyData

namespace SecondHurewicz.SimplyConnected.VertexHomotopyData.mk
export Hurewicz.DegreeTwo.SimplyConnected.VertexHomotopyData.mk (
  inj
  injEq
  noConfusion
  sizeOf_spec
)
end SecondHurewicz.SimplyConnected.VertexHomotopyData.mk

namespace SecondHurewicz.SimplyConnected.VerticesBased
export Hurewicz.DegreeTwo.SimplyConnected.VerticesBased (
  face
)
end SecondHurewicz.SimplyConnected.VerticesBased

namespace SecondHurewicz.SimplyConnected.vertexStraighteningData
export Hurewicz.DegreeTwo.SimplyConnected.vertexStraighteningData (
  match_1
)
end SecondHurewicz.SimplyConnected.vertexStraighteningData

alias SecondHurewicz.SimplyConnected.basedTriangleClass.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.basedTriangleClass.eq_1
alias SecondHurewicz.SimplyConnected.bottomProductDegenerate.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.bottomProductDegenerate.eq_1
alias SecondHurewicz.SimplyConnected.chosenBasePath.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.chosenBasePath.eq_1
alias SecondHurewicz.SimplyConnected.chosenNullHomotopy.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.chosenNullHomotopy.eq_1
alias SecondHurewicz.SimplyConnected.edgeNullHomotopy.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.edgeNullHomotopy.congr_simp
alias SecondHurewicz.SimplyConnected.edgeStraighteningHomotopy.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.edgeStraighteningHomotopy.eq_1
alias SecondHurewicz.SimplyConnected.extendBoundaryHomotopy.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.extendBoundaryHomotopy.congr_simp
alias SecondHurewicz.SimplyConnected.leftProductDegenerate.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.leftProductDegenerate.eq_1
alias SecondHurewicz.SimplyConnected.lowerProductTriangle.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.lowerProductTriangle.eq_1
alias SecondHurewicz.SimplyConnected.lowerSquareTriangle.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.lowerSquareTriangle.eq_1
alias SecondHurewicz.SimplyConnected.normalizedTetrahedron.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.normalizedTetrahedron.congr_simp
alias SecondHurewicz.SimplyConnected.normalizedTriangle.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.normalizedTriangle.congr_simp
alias SecondHurewicz.SimplyConnected.normalizedTriangleCycleOperator.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.normalizedTriangleCycleOperator.congr_simp
alias SecondHurewicz.SimplyConnected.normalizedTwoChain.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.normalizedTwoChain.congr_simp
alias SecondHurewicz.SimplyConnected.rotationBlend.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.rotationBlend.eq_1
alias SecondHurewicz.SimplyConnected.rotationCentered.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.rotationCentered.eq_1
alias SecondHurewicz.SimplyConnected.rotationDenominator.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.rotationDenominator.eq_1
alias SecondHurewicz.SimplyConnected.rotationNormalized.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.rotationNormalized.eq_1
alias SecondHurewicz.SimplyConnected.rotationVector.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.rotationVector.eq_1
alias SecondHurewicz.SimplyConnected.secondHomologyDesc.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.secondHomologyDesc.congr_simp
alias SecondHurewicz.SimplyConnected.simplexBoundary.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.simplexBoundary.eq_1
alias SecondHurewicz.SimplyConnected.simplexPrism.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.simplexPrism.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionBlend.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionBlend.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionLowerBasedTriangle.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.subdivisionLowerBasedTriangle.congr_simp
alias SecondHurewicz.SimplyConnected.subdivisionLowerProductLoop.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.subdivisionLowerProductLoop.congr_simp
alias SecondHurewicz.SimplyConnected.subdivisionLowerProductLoop.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionLowerProductLoop.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionLowerProductMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionLowerProductMap.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionLowerTriangleLoop.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.subdivisionLowerTriangleLoop.congr_simp
alias SecondHurewicz.SimplyConnected.subdivisionLowerTriangleMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionLowerTriangleMap.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionPullbackLoop.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionPullbackLoop.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionSubMin.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionSubMin.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperConeMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperConeMap.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperNegativeBasedTriangle.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperNegativeBasedTriangle.congr_simp
alias SecondHurewicz.SimplyConnected.subdivisionUpperNegativeLoop.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperNegativeLoop.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperNegativeMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperNegativeMap.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperNegativeReversedMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperNegativeReversedMap.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperPositiveBasedTriangle.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperPositiveBasedTriangle.congr_simp
alias SecondHurewicz.SimplyConnected.subdivisionUpperPositiveSquareTriangle.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperPositiveSquareTriangle.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperProductLoop.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperProductLoop.congr_simp
alias SecondHurewicz.SimplyConnected.subdivisionUpperProductLoop.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperProductLoop.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperProductMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperProductMap.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionUpperTriangleLoop.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperTriangleLoop.congr_simp
alias SecondHurewicz.SimplyConnected.subdivisionUpperTriangleMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionUpperTriangleMap.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionWarpCoordinate.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionWarpCoordinate.eq_1
alias SecondHurewicz.SimplyConnected.subdivisionWarpMap.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.subdivisionWarpMap.eq_1
alias SecondHurewicz.SimplyConnected.tetrahedronQuadrilateralA.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.tetrahedronQuadrilateralA.eq_1
alias SecondHurewicz.SimplyConnected.triangleClassOperator.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.triangleClassOperator.congr_simp
alias SecondHurewicz.SimplyConnected.triangleEdgeStraighteningHomotopy.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.triangleEdgeStraighteningHomotopy.congr_simp
alias SecondHurewicz.SimplyConnected.upperProductTriangle.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.upperProductTriangle.eq_1
alias SecondHurewicz.SimplyConnected.upperSquareTriangle.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.upperSquareTriangle.eq_1
alias SecondHurewicz.SimplyConnected.vertexStepHomotopy.eq_1 := Hurewicz.DegreeTwo.SimplyConnected.vertexStepHomotopy.eq_1
alias SecondHurewicz.SimplyConnected.vertexStraighteningHomotopy.congr_simp := Hurewicz.DegreeTwo.SimplyConnected.vertexStraighteningHomotopy.congr_simp
alias SecondHurewicz.fundamentalSquareChain.eq_1 := Hurewicz.DegreeTwo.fundamentalSquareChain.eq_1
alias SecondHurewicz.intervalChain.eq_1 := Hurewicz.DegreeTwo.intervalChain.eq_1
alias SecondHurewicz.productSquareChain.eq_1 := Hurewicz.DegreeTwo.productSquareChain.eq_1
alias SecondHurewicz.squareChain.eq_1 := Hurewicz.DegreeTwo.squareChain.eq_1
alias SecondHurewicz.squareCoordinates.eq_1 := Hurewicz.DegreeTwo.squareCoordinates.eq_1
